### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by schrodincat** [rafaelrinaldi/pure#100]
Add CONTRIBUTING.md (see https://blog.github.com/2012-09-17-contributing-guidelines/) to the project with code conventions described here: https://github.com/rafaelrinaldi/pure/issues/99

**Comment by edouard-lopez** [comment]
The _pure_ community is still pretty small, I believe we can discuss issues/PR and design rather than throwing a modern "RTFM!" at contributors.

Upvote issue if you feel we need it.

**Comment by schrodincat** [comment]
I just thought it would be logical place for code conventions to be instead of editing issue every time
