### ISSUE TITLE
Issue installing via OMF

### ISSUE THREAD

**Issue by rafaelrinaldi** [rafaelrinaldi/pure#102]
For some reason when installing (or updating) via OMF, will return errors and break the prompt. This is what I see:

```
✔ pure successfully installed.
Installation successful!
test: Missing argument at index 2
test: Missing argument at index 2
test: Missing argument at index 2
```

**Comment by rafaelrinaldi** [comment]
Nevermind, just realized this is a known issue that is fixed by symlinking it.

**Comment by tucq88** [comment]
How did you fix it ? Can't find the `known issue` you mentioned

**Comment by edouard-lopez** [comment]
@tucq88 it's in the [OMF's section of the readme](https://github.com/rafaelrinaldi/pure/)
