### ISSUE TITLE
Weird output for command duration on Fish 3

### ISSUE THREAD

**Issue by sholladay** [rafaelrinaldi/pure#107]
Hello! 👋 

Thanks for this awesome project. I have been a happy user for about a year now.

I just upgraded to [Fish 3](https://github.com/fish-shell/fish-shell/releases/tag/3.0.0). Obviously it's very new and I wasn't expecting the prompt to even work necessarily. So far, on the surface at least, it seems to work fine, but I did encounter a display bug with the feature that shows the duration of the previous command.

```fish
❯ time sleep 1
        1.00 real         0.00 user         0.00 sys

/tmp 0.000012d 0.000281h 0.016883m
❯ time sleep 10
       10.00 real         0.00 user         0.00 sys

/tmp 0.000116d 0.002779h 0.166767m 10.006s
❯
```

I'm not sure what causes it to repeat the time in various fractions. I find it amusing, though. We can say it's a feature... 😄

**Comment by edouard-lopez** [comment]
Hi @sholladay,
Thanks for testing the bleeding edge fish version :+1: 

Could you give the value of `$pure_command_max_exec_time` and `$CMD_DURATION`?

    echo $pure_command_max_exec_time $CMD_DURATION

Displaying the command duration is determined by:
* [_pure_prompt_command_duration.fish](https://github.com/rafaelrinaldi/pure/blob/master/functions/_pure_prompt_command_duration.fish) and [tested](https://github.com/rafaelrinaldi/pure/pull/96/files#diff-24)
* [_pure_format_time.fish](https://github.com/rafaelrinaldi/pure/blob/master/functions/_pure_format_time.fish) and [tested](https://github.com/rafaelrinaldi/pure/pull/96/files#diff-18)

**Comment by edouard-lopez** [comment]
@sholladay What is the **exact fish version** you are running?

    fish --version

There is commits going [back](https://github.com/fish-shell/fish-shell/issues/4414#issuecomment-375892492) and [forth](https://github.com/jorgebucaran/fish-mono/pull/5) between `$CMD_DURATION` and lowercase `$cmd_duration`. 

@faho Could you clarify how we should manage this?

**Comment by faho** [comment]
>@faho Could you clarify how we should manage this?

It already _is_ managed.

This happens because the new `math` builtin defaults to float. To get integers like before, you have to add an explicit scale argument.

Which I've already done in d0a6427cd7f5498c9a33061c9dfdf43a5c4ffe92.

@sholladay: Please upgrade pure!

**Comment by faho** [comment]
Oh, and "$cmd_duration" was a mistake that we've gone back on. There is no release with that name, so please continue to use $CMD_DURATION everywhere!

**Comment by sholladay** [comment]
Ooof. Don't do what I did. I ran `fisher up` to update `pure` and everything went to hell. First follow the [migration guide for fisher v3](https://github.com/jorgebucaran/fisher/issues/450)! There is a section on how to get yourself out of that mess if it's too late.

Anyway, I got it all sorted out. Fish, fisher, and pure are all up to date and working well. 😀 

Thanks for your help, all!

```fish
❯ fish --version
fish, version 3.0.0

/tmp
❯ fisher --version
fisher version 3.1.1 ~/.config/fish/functions/fisher.fish

/tmp
❯ time sleep 10
       10.00 real         0.00 user         0.00 sys

/tmp 10s
❯ echo $pure_command_max_exec_time $CMD_DURATION
5 10018
```
