### ISSUE TITLE
fatal: no such branch: 'HEAD...' on empty repository

### ISSUE THREAD

**Issue by joseluisq** [rafaelrinaldi/pure#11]
When I clone an empty repository `pure` throws me an error: 

*No such branch: 'HEAD...'*
![image](https://cloud.githubusercontent.com/assets/1700322/12364912/725e4e94-bb9f-11e5-8629-00ac17333a24.png)

**Comment by oranja** [comment]
I'm trying to see if this is OS X specific.
I created an empty git repository locally (`git init test`) and didn't get any error on `cd test/`.
Does it happen to you when you do `git init`? or only specifically when you `clone` an empty repository?

Also, what's your `git --version`?

**Comment by joseluisq** [comment]
Apparently this occurs with bitbucket empty repo. (tested)

```sh
$ git version
git version 2.5.0
```

Here my screenshot:
![image](https://cloud.githubusercontent.com/assets/1700322/12425172/89605740-bea1-11e5-9cc9-3b204156add3.png)

**Comment by oranja** [comment]
Reproduced this on my machine (Fedora 23, 64-bit, git 2.5.0) as well.
I think I found a fix. Will submit a PR for review in a few moments.

**Comment by joseluisq** [comment]
:+1:
