### ISSUE TITLE
iTerm2 shell integration broken.

### ISSUE THREAD

**Issue by JunJi-JiaYue** [rafaelrinaldi/pure#116]
* fish 3.0.0
* iTerm2 3.2.6
  * with [Shell Integration](https://www.iterm2.com/3.0/documentation-shell-integration.html) ([.iterm2_shell_integration.fish](https://iterm2.com/shell_integration/fish))
* pure 1.13.0 (installed through fisher 3.2.2)

```
$ fish
functions: Function 'fish_mode_prompt' does not exist
~/.iterm2_shell_integration.fish (line 59):
  functions -c fish_mode_prompt iterm2_fish_mode_prompt
  ^
from sourcing file ~/.iterm2_shell_integration.fish
	called on line 7 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup


       functions - print or erase functions

   Synopsis
       functions [ -a | --all ] [ -n | --names ]
       functions [ -D | --details ] [ -v ] FUNCTION
       functions -c OLDNAME NEWNAME
       functions -d DESCRIPTION FUNCTION
       functions [ -e | -q ] FUNCTIONS...

functions: Type 'help functions' for related documentation

fish: Unknown command 'iterm2_fish_mode_prompt'
~/.iterm2_shell_integration.fish (line 69):
     iterm2_fish_mode_prompt
     ^
in function 'fish_mode_prompt'
	called on standard input

in command substitution
	called on standard input

~
❯
```

```
❯ echo $pure_version
1.13.0
fish: Unknown command 'iterm2_fish_mode_prompt'
~/.iterm2_shell_integration.fish (line 69):
     iterm2_fish_mode_prompt
     ^
in function 'fish_mode_prompt'
	called on standard input

in command substitution
	called on standard input


~
❯
```

my `config.fish`:
```
test -e {$HOME}/.iterm2_shell_integration.fish ; and source {$HOME}/.iterm2_shell_integration.fish
```

**Comment by edouard-lopez** [comment]
@schrodincat By misplaced, do you mean it's an installer issue? If so, it needs to be reported to `fisher` while we fix our installer.

**Comment by schrodincat** [comment]
> By misplaced, do you mean it's an installer issue?

No, what I mean it doesn't align properly:
<img width="682" alt="screenshot 2019-01-09 at 17 54 02" src="https://user-images.githubusercontent.com/13354491/50907119-a2e23000-1437-11e9-9d40-99d7aae46c73.png">

**Comment by edouard-lopez** [comment]
@schrodincat I won't be able to help here, I'm on Linux

**Comment by JunJi-JiaYue** [comment]
I have installed it through fisher.

**Comment by sanyer** [comment]
@edouard-lopez was this fixed? I still see that error message.

**Comment by edouard-lopez** [comment]
My bad, thought that @JunJi-JiaYue  last message meant it was fixed

**Comment by edouard-lopez** [comment]
@JunJi-JiaYue @sanyer could you clarify your bug behavior?

### 'fish_mode_prompt' does not exist
If the issue is `functions: Function 'fish_mode_prompt' does not exist` then create a file with this name in your home directory:

    echo '' > $HOME/.config/fish/functions/fish_mode_prompt.fish

### Auto-loading function
If you want to leverage [auto-loading mechanism](https://fishshell.com/docs/current/index.html#syntax-function-autoloading), `.iterm2_shell_integration.fish` should be in `~/.config/fish/functions` or one of the directory set in or `$fish_function_path`

### Fish issue?

You might look at `fish` issues. For instance, this one https://github.com/fish-shell/fish-shell/issues/2692#issuecomment-186821513 has a snippet defining `iterm2_fish_mode_prompt` based on `fish_mode_prompt`.

Sorry I can't help more as it's MacOS-related issue.

**Comment by sanyer** [comment]
@edouard-lopez well, removing the file `fish_mode_prompt.fish` actually helps

**Comment by JunJi-JiaYue** [comment]
Sorry for my late reply.
Defining empty `fish_mode_prompt` function in my `config.fish` helps.

**Comment by sanyer** [comment]
Seems more like a workaround. Maybe at least write about this in README.md?

**Comment by edouard-lopez** [comment]
From what you described, it's a fish-related configuration issue. 
I'm in favour to keep the readme concise, as we have issue tracker for this kind of corner case.
Probably a good idea will be to submit a PR to update fish documentation.

**Comment by schrodincat** [comment]
@sanyer that’s not `fish` issue, but rather iTerm integration script issue. I’ll tackle this in future releases, for now, please use proposed workaround.

@edouard-lopez what is the purpose of `fish_mode_prompt` function for us anyway? Do we need empty `fish_mode_prompt.fish` without function definition? Is this even correct to leave empty file without actual function definition? Maybe we should at least declare empty `fish_mode_prompt` function there?

**Comment by edouard-lopez** [comment]
@schrodincat we don't use `fish_mode_prompt` that's why I said it's not a _pure_ issue (as one originating from our code).
We could add an empty function as it's a low cost addition

**Comment by sanyer** [comment]
yeah, so other themes I used had `fish_mode_prompt.fish` with empty `fish_mode_prompt` function

**Comment by sanyer** [comment]
cool, thanks @schrodincat and @edouard-lopez 👍
