### ISSUE TITLE
Prefix prompt when logged in as root

### ISSUE THREAD

**Issue by edouard-lopez** [rafaelrinaldi/pure#117]
This is a [feature on the `zsh` version](https://github.com/sindresorhus/pure/wiki/Customizations,-hacks-and-tweaks#prefix-prompt-when-logged-in-as-root):

```zsh
# For completeness, start by closing the original %F{magenta} with %f.
# The final %f will be added by the PROMPT definition.
PURE_PROMPT_SYMBOL='%f%F{red}#%f %F{magenta}❯'


```

**Comment by rafaelrinaldi** [comment]
Nice catch! I will work on this.

**Comment by eoli3n** [comment]
Any update on this ?

**Comment by eoli3n** [comment]
Workaround with a fish script ``~/.config/fish/conf.d/pure-symbol.fish``
```bash
if test $USER = root
  set pure_symbol_prompt "•"
else
  set pure_symbol_prompt "➜"
end
```
