### ISSUE TITLE
Report the Max Exec Time for commands (enhancement)

### ISSUE THREAD

**Issue by joseluisq** [rafaelrinaldi/pure#13]
I think it's necessary to report *"max execution time"* of commands, something like:

```sh
~
> npm install
...
~ 20s
>
```

**Comment by oranja** [comment]
I see execution time reported some times, but not all of the time... There's a chance that this is just when and how Fish reports time.

**Comment by joseluisq** [comment]
In my case I can't see the time exec :(

**Comment by rafaelrinaldi** [comment]
There's a threshold we use to display the execution time of failed commands. Feel free to customize it but I want to keep the way it is right now to be consistent to the original theme.

What would be nice is to have an easy way to customize the setup. It should be easy to do but I haven't had time to tackle it yet.

**Comment by rafaelrinaldi** [comment]
Closing the issue since I've already explaining this request is out of the scope of the project. Would love some help in making the theme easier to customize though.
