### ISSUE TITLE
Command Color Blue

### ISSUE THREAD

**Issue by gtalarico** [rafaelrinaldi/pure#133]
Hello and thanks for this great theme. 
I am really enjoying the latest release with customizable colors!

I am having an issue with the command color setting up the theme on new MacOs
After installing a iterm2, fish, and then adding pure using fisher, 
the default command color is showing a a default blue, 
as set by the default `fish_variables` file. 
(The blue used is not on my shell color preset.)

```fish
#.config/fish/fish_variables
...
SETUVAR fish_color_command:005fd7
...
```

If I delete `fish_variables`, it gets recreated.
The only solution I have found is to edit `fish_color_command` to `white`

Is this a bug? I am fairly new to fish, so apologies if I am missing something elementary.

Thanks!

<img width="905" alt="screen shot 2019-01-13 at 8 50 22 pm" src="https://user-images.githubusercontent.com/9513968/51096934-215f0a80-1775-11e9-9693-d6c2ab072d94.png">
<img width="872" alt="screen shot 2019-01-13 at 8 52 39 pm" src="https://user-images.githubusercontent.com/9513968/51096941-3b98e880-1775-11e9-93f0-d530eabd4c0c.png">

**Comment by edouard-lopez** [comment]
Hello @gtalarico,
Thanks for the kind words, always appreciated :)

We don't manipulate `fish_color_` variables, there are from `fish` directly. The solution you find seem reasonnable enough. 

Anyway, I would recommend to [declare your issue on `fish` issue tracker](https://github.com/fish-shell/fish-shell/issues/new) and cross-referencing this one (_e.g._ with this code `rafaelrinaldi/pure#133`). Re-open if need be.
