### ISSUE TITLE
Pure fish logo

### ISSUE THREAD

**Issue by edouard-lopez** [rafaelrinaldi/pure#136]
Would you be interested to have a logo for the project?

Played a bit with the prompt symbol. Color are based on [`ayu-mirage`](https://github.com/weirdpattern/hyper-ayu-mirage) and [`ayu-light`](https://github.com/weirdpattern/hyper-ayu-light) colorscheme.

![logo-small](https://user-images.githubusercontent.com/1212392/51947579-a3ae2680-2425-11e9-8c94-08a60611afd4.png)

Upvote the one you prefer or make a proposal :heart_eyes: 

[SVG source](https://gist.github.com/edouard-lopez/7735bce4b17d6c4551cd15d9c1acd0d0) is available as a gist.

**Comment by edouard-lopez** [comment]
![logo-magenta](https://user-images.githubusercontent.com/1212392/51947241-714ff980-2424-11e9-901e-8a65cd8fe6cd.png)

**Comment by edouard-lopez** [comment]
![logo-red](https://user-images.githubusercontent.com/1212392/51947266-8af14100-2424-11e9-984a-96dc8c25a376.png)

**Comment by edouard-lopez** [comment]
![logo-yellow](https://user-images.githubusercontent.com/1212392/51947273-93e21280-2424-11e9-8a0b-f58d2daac37c.png)

**Comment by edouard-lopez** [comment]
![logo-cyan](https://user-images.githubusercontent.com/1212392/51947296-a6f4e280-2424-11e9-971b-8468d194daad.png)

**Comment by schrodincat** [comment]
Probably, should be with our default color... I also like orange one, though

**Comment by edouard-lopez** [comment]
Adding a `_` was not conclusive that why I didn't submit the version with it.

**Comment by edouard-lopez** [comment]
I'm closing as idle for more than a year now.
Feel free to reopen

**Comment by edouard-lopez** [comment]
## Only logo
![pure-logo](https://github.com/pure-fish/pure/assets/1212392/bf052659-e38f-4329-bb7e-2d9d395f5bd7)

## Template
![pure-logos-template](https://github.com/pure-fish/pure/assets/1212392/60f4bb2b-60b2-4fa1-94ab-2d8fedc7f288)
