### ISSUE TITLE
Trouble when $HOME points to a symlink

### ISSUE THREAD

**Issue by jurf** [rafaelrinaldi/pure#137]
Hi,

I currently run [Silverblue](https://silverblue.fedoraproject.org/), where `$HOME` points to `/home/<username>` (as is normal), but that directory is a symlink to `/var/home` (the base image is immutable, so everything that changes lives under `/var`).

Pure however handles this a bit unfortunately:

```
/var~
❯ 
```

Cheers.

**Comment by edouard-lopez** [comment]
Hi @jurf,
Could you tell us what is the content of `$HOME` and `$PWD` when in your home directory? That will help us add test to support your scenario. 

That's probably related to how `_pure_parse_directory` works:
* https://github.com/rafaelrinaldi/pure/blob/master/functions/_pure_parse_directory.fish
* https://github.com/rafaelrinaldi/pure/blob/master/tests/_pure_parse_directory.test.fish

**Comment by jurf** [comment]
Hey, thanks for the reply. This are the variables in question:

```
❯ export
…
HOME /home/jurf
PWD /var/home/jurf
…
```

**Comment by edouard-lopez** [comment]
Thanks,
the behaviour is the expected one in light to our current code.
I'm in favour to support this as an explicit rule, _i.e._ only symlink to `/var/$HOME` as we can use a simple glob expansion/regex to do it.

Cc @schrodincat @rafaelrinaldi

**Comment by jurf** [comment]
Hm, turns out that the latest Silverblue uses `$HOME=/home/<user>` again.

I do get the directory printed twice, but that is a different issue, I guess.

**Comment by edouard-lopez** [comment]
I'm closing as `$HOME` behaviour is back to standard. 

Feel free to open another issue
