### ISSUE TITLE
vi mode indicator

### ISSUE THREAD

**Issue by codesections** [rafaelrinaldi/pure#139]
Thanks for this project—I just switched from Zsh to Fish, and I'm not sure I would have done so if it meant needing to give up the wonderful `❯`.

However, I also use the vim keybindings in Fish, and I noticed that this project indicates the current mode a bit differently than the Zsh Pure does.  Specifically, our version prints out the full default `[N]` or other letter to indicate the current mode.  In contrast, the Zsh version flips the `❯` to a `❮` for every non-insert mode.

IMO, this looks a lot better, fits in with the rest of the prompt, and doesn't sacrifice any useful info.  I've already modified my version of the prompt to duplicate this behavior, and would be happy to submit a PR upstream if y'all would be interested in it.

If so, should it be default behavior or user-configurable?  It's tempting to make everything user-configurable, but it can also be overwhelming to expose too many knobs and dials.

**Comment by edouard-lopez** [comment]
Hello @codesections,
Glad we ease the transition to `fish` :v: 

---
Disclaimer: I'm not a `vi`-mode user myself.

Having similar behaviour than the [`zsh` version](https://github.com/sindresorhus/pure) is something we aim for as we recently merged several PRs to fill the gap between our version and the one from sindresorhus. 

So my recommendation would be to set the behavior you described as the default and add a flag to switch back to the fish default behavior, _e.g._:

    pure_reverse_prompt_symbol_in_vimode true

We are currently relying on the default behavior of `fish` by calling [`fish_default_mode_prompt`](https://github.com/rafaelrinaldi/pure/blob/master/functions/_pure_prompt_vimode.fish) in [__pure_prompt_vimode.fish_](https://github.com/rafaelrinaldi/pure/blob/master/functions/_pure_prompt_vimode.fish):
https://github.com/rafaelrinaldi/pure/blob/1fabe247ce13a1cb4d3de3a219f0116f6af3bb43/functions/_pure_prompt_vimode.fish#L2

:information_source: Have a look at our [configuration revamp](https://github.com/rafaelrinaldi/pure/issues/130) and [contributing guide](https://github.com/rafaelrinaldi/pure/blob/578782aac0/CONTRIBUTING.md) to get familiar with naming convention.

cc @schrodincat @rafaelrinaldi
