### ISSUE TITLE
Git branch and status not shown

### ISSUE THREAD

**Issue by voider1** [rafaelrinaldi/pure#149]
I installed Prompt via omf and made the symlink, vi-mode works nicely with the prompt, but the Git symbols and branch are not shown. Any ideas how I could fix this?

**Comment by edouard-lopez** [comment]
Hello @voider1,
Is the link valid? _i.e._ linking to the correct directory? 

Could you give us the value for:

    echo $pure_version
    echo $pure_symbol_git_dirty
    _pure_prompt_git_branch  # function to call

To be sure, got information only when you're on a git repository. 

Could you create a minimal setup to reproduce your issue using our [docker images](https://github.com/rafaelrinaldi/pure/wiki/Testing-pure-for-dummies)?

**Comment by voider1** [comment]
Alright, so after some investigation it seems that the text and everything is in fact shown, but it's shown in the same color as the background, I'm using Solarized Dark. So that's why it's not shown. Any way to fix this?

**Comment by voider1** [comment]
Update: I fixed it, so apparently the colors my terminal was using and the colors Fish wanted to use didn't align. I resolved this and now everything is shown.
