### ISSUE TITLE
Git branch not showing output

### ISSUE THREAD

**Issue by heydonovan** [rafaelrinaldi/pure#161]
![Screen Shot 2019-04-01 at 12 31 38 PM](https://user-images.githubusercontent.com/918946/55347328-2b420100-547a-11e9-83f5-85a461567026.png)

I'm not sure if the feature needs to be turned on, but the README make it sound like such an option would be turned on in the `pure.fish` file:

```
❯ cat $HOME/.config/fish/conf.d/pure.fish
[bat error]: '/Users/donovanhernandez/.config/fish/conf.d/pure.fish': No such file or directory (os error 2)
```

```
❯ echo $pure_version
2.1.2

❯ fish --version
fish, version 3.0.2

❯ uname -a
Darwin Donovan-Hernandez---MBP018 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
```

**Comment by schrodincat** [comment]
What installation method did you used?

**Comment by schrodincat** [comment]
@heydonovan I can confirm that manual installation method is broken.

While we are on it, you can install `pure` with [`fisher`](https://github.com/jorgebucaran/fisher), it's very lightweight package manager for `fish`.

**Comment by edouard-lopez** [comment]
@schrodincat is it still broken after merging #159 ?
