### ISSUE TITLE
 Error test: Missing argument at index 2 with virtualfish

### ISSUE THREAD

**Issue by edouard-lopez** [rafaelrinaldi/pure#17]
After installing [virtualfish](/adambrenecki/virtualfish) and [customizing my `fish_prompt`](https://virtualfish.readthedocs.org/en/latest/install.html#customizing-your-fish-prompt) as shown in the documentation with my [`omf` theme `pure`](https://github.com/rafaelrinaldi/pure) I got error:

    test: Missing argument at index 2

I tried with another theme (`flash`) and got event more error.

### steps 

I edited the [fish_prompt](https://github.com/rafaelrinaldi/pure/blob/master/fish_prompt.fish#L106) as follow:

    funced fish_prompt
    # add lines, then save and quit vim
    funcsave fish_prompt
    # Ctrl+D to quit tmux tab
    # open new tab, get the error

### Question 

How can I solve this issue?

### See also

* issue [virtualfish #79](/adambrenecki/virtualfish/issues/79).

**Comment by scorphus** [comment]
@edouard-lopez: there are other themes that support virtualfish, such as `bobthefish` and `scorphish`. If you wish to have current active virtualenv in your pure prompt, just make it look like [this](https://gist.github.com/scorphus/82624ba92c7f3d0c0758#file-fish_prompt-fish-L51-L54).

@rafaelrinaldi: even this being port from ZSH theme, if you'd like to add support to virtualfish, a pull request is on the way :smile:

**Comment by rafaelrinaldi** [comment]
@scorphus We want to stay consistent with the original theme. You can add to your custom settings anyway.

**Comment by rafaelrinaldi** [comment]
@edouard-lopez Isn't there a way to simply bypass this check? Not sure how to do it but ideally the theme shouldn't bitch about it.

**Comment by edouard-lopez** [comment]
Solved by editing `~/.config/fish/functions/fish_prompt.fish` and adding the following:
```
  if set -q VIRTUAL_ENV
    set prompt $prompt "$color_gray("(basename "$VIRTUAL_ENV")")$color_normal \n"
  end
```

Seem the `funced fish_prompt` was not the correct way to do it.

However this is not reinstall-proof…
