### ISSUE TITLE
`~/.config/fish/conf.d` directory install issue

### ISSUE THREAD

**Issue by ntwb** [rafaelrinaldi/pure#170]
## Env

**Pure**

    echo $pure_version - 2.1.5

**Fish**

    fish --version - 3.0.2

**OS/distribution**

    lsb_release -a - fish: Unknown command lsb_release

    macOS Mojave

The change https://github.com/rafaelrinaldi/pure/commit/6b32805a355a0692a9a0b4495873a04043717e99#diff-11542d6bb9f3baecffc1be92684045bbR57 in the install procedure:

> `ln -sf $PURE_INSTALL_DIR/conf.d/* $FISH_CONFIG_DIR/conf.d/

The above line caused an issue during install because I previously did not have a `conf.d` folder under my `fish` folder, once adding it so that I now have `~/.config/fish/conf.d` the install was then successful.

Maybe a check for if the directory exists would be helpful, I suspect if it doesn't creating it should also be fine.

p.s. As an aside, why does Pure v2 now add a bunch of symlinks adding files to the _root_ of my `~/.config/fish` folder? I'd rather I didn't have to add bunch of manual exludes to my `.gitignore` for my Fish config _dotfiles_ setup!

**Comment by edouard-lopez** [comment]
@ntwb Thanks for taking the time to give us feedback, and finding a solution :heart: 

You are absolutely right, I'm currently mocking those directories in #169.

@rafaelrinaldi @schrodincat 
Maintaining the manual installer is more and more painful, I'm thinking about deprecating it in favour of `fisher` which work nicely. 

What do you think?

**Comment by ntwb** [comment]
> Maintaining the manual installer is more and more painful, I'm thinking about deprecating it in favour of fisher which work nicely.

If that'll help avoid symlinking the files in the root fish config folder, I'm +1

**Comment by edouard-lopez** [comment]
see #171

**Comment by Plastix** [comment]
I am trying to install this plugin using Fundle (https://github.com/danhper/fundle). Is this related to why I cannot get the prompt working under Fundle?

**Comment by edouard-lopez** [comment]
@Plastix I [disable `fundle` test](https://github.com/rafaelrinaldi/pure/blob/8c274175099c82e5a6a8d563ba8b9e887eef1104/tests/installation-methods.test.fish#L70-L82) cause they were broken and wasn't able to fix it. 

Create a dedicated issue with some information in order to help us debug.

**Comment by nesl247** [comment]
See #172 for fundle.
