### ISSUE TITLE
Prompt does not work in fundle

### ISSUE THREAD

**Issue by nesl247** [rafaelrinaldi/pure#172]
## Env

**Pure**: 2.1.5

**Fish**: 3.0.2

**OS/distribution**: macOS 10.14

The prompt used to work in 1.0, but with 2.0, it does not change the prompt. I know that it loads because the functions are available, but there are likely some files that are in the wrong directory.

**Comment by nesl247** [comment]
And confirmed. Move all of the `*.fish` files in `/` to `functions/` and it works. This is actually the same exact thing when I reported this in 1.0 #76.

**Comment by edouard-lopez** [comment]
Thanks @nesl247, `fundle` install tests kept failing, I wasn't able to fix them in a reasonable time. So we can't guarantee `fundle` support. 

Does it work with [`fisher` or manual install](https://github.com/rafaelrinaldi/pure/blob/master/README.md#manually)?

**Comment by nesl247** [comment]
It works after I moved all the files to `functions/`. Having them in the root of the repo is the problem. It does not follow fish-shell's own autoloading system. Fundle does follow it though.

**Comment by edouard-lopez** [comment]
I guess you meant _moving all the `./fish_.fish` to `./functions/` as we already have all `pure_*.fish` file under `./functions/`.

Would you be interested to submit a PR?

**Comment by nesl247** [comment]
Correct as mentioned [here](https://github.com/rafaelrinaldi/pure/issues/172#issuecomment-495262834). I don't mind submitting a PR, but I can't test that it works for all the different systems.

**Comment by edouard-lopez** [comment]
That's why we have CI :)

We use [`fishtape`](https://github.com/fisherman/fishtape) to write our tests. Guve it a try and let me know if you need help.

**Comment by broizter** [comment]
Any news on this? Looks like the pull request is ready to go.

**Comment by schrodincat** [comment]
Fixed in `2.5.1`
