### ISSUE TITLE
Print warns  when clone an empty repo

### ISSUE THREAD

**Issue by fundon** [rafaelrinaldi/pure#179]
1. Create an repo on GitHub
2. Clone the repo

```sh
~/Dev/workspaces
λ git clone git@github.com:fundon/fish.git
Cloning into 'a'...
warning: You appear to have cloned an empty repository.

~/Dev/workspaces
λ cd fish

fatal: no such branch: 'HEAD...'
test: Missing argument at index 2
test: Missing argument at index 2
fatal: no such branch: 'HEAD...'
test: Missing argument at index 2
test: Missing argument at index 2
```

3. exec any commands, print above always

## Env

**Pure**

    echo $pure_version
    2.1.5

**Fish**

    fish --version
    fish, version 3.0.2

**OS/distribution**

    lsb_release -a
    macOS 10.15 19A501i

**Comment by edouard-lopez** [comment]
Thanks @fundon, 

I reproduce with when cloning:

	git clone git@github.com:edouard-lopez/empty-repo.git

Come from https://github.com/rafaelrinaldi/pure/blob/c506bd00eb93a740cfa96e280b5102939dbd211a/functions/_pure_prompt_git_pending_commits.fish#L7

We add a file to our fake repo in our test setup, https://github.com/rafaelrinaldi/pure/blob/c506bd00eb93a740cfa96e280b5102939dbd211a/tests/_pure_prompt_git_pending_commits.test.fish#L17-L19

We should either:
* add the file on a test case base
* remove the file in a dedicated test to trigger the error and fix it

Would you like to submit a PR to fix this? I will guide you if need be.

**Comment by fundon** [comment]
Ok, i create a PR
