### ISSUE TITLE
Fish's Native Vi Mode Does Not Display

### ISSUE THREAD

**Issue by BrunoRoque06** [rafaelrinaldi/pure#181]
**Pure**
2.1.7

**Fish**
3.0.2

**OS/distribution**
MacOS/Arch Linux

**Description**

The following parameter does not work as expected:

```
set -U pure_reverse_prompt_symbol_in_vimode false
```

as the prompt does not display `fish_default_mode_prompt`.

**Possible Solution**

I believe replacing this (in `_pure_prompt_vimode.fish:2`):

```
if test ! $pure_reverse_prompt_symbol_in_vimode
```

by something like this:

```
if test "$pure_reverse_prompt_symbol_in_vimode" = false
```

should fix it.

**Comment by edouard-lopez** [comment]
Thanks I created a pull request based on your feedback #183
