### ISSUE TITLE
Installation instructions at releases are wrong

### ISSUE THREAD

**Issue by limakzi** [rafaelrinaldi/pure#184]
## Envrafaelrinaldi/pure

Installation instruction at `releases` page is wrong.
https://github.com/rafaelrinaldi/pure/releases

It is:
```
fisher add fisher add rafaelrinaldi/pure
```

It should be:
```
fisher add rafaelrinaldi/pure
```

**Pure**

Not relevant.

**Fish**

 Not relevant.

**OS/distribution**

Not relevant.

**Comment by edouard-lopez** [comment]
@limakzi thanks, that's fixed
