### ISSUE TITLE
Right prompt doesn't handle command substitution

### ISSUE THREAD

**Issue by Sohex** [rafaelrinaldi/pure#186]
## Env

**Pure**

    echo $pure_version
    2.1.8

**Fish**

    fish --version
    fish, version 3.0.2

**OS/distribution**

    lsb_release -a
    OS X Mojave 10.14.5

## Issue
When setting the right prompt with `pure_right_prompt` the value is only set once when config.fish is sourced, preventing prompts dependent upon command substitution from updating. In this case I want to set my right prompt to indicate my kubernetes context and namespace using `https://github.com/aluxian/fish-kube-prompt`

If I set the prompt as such:
```
set pure_right_prompt (__kube_prompt)
```
the prompt only displays what is returned when config.fish is sourced and it won't reflect changes to the output of the provided command.

**Comment by edouard-lopez** [comment]
Hello @Sohex, thanks for the feedback.
Could you try with another command than `__kube_prompt` to see if there is some cache happening.
I will try to look into this before the weekend.

**Comment by filipebarros** [comment]
The right prompt will only run on the first execution (it doesn't run every time you execute a command). If there's a way to work around it, I'd be happy to help or implement it (I added it so, I think it's my fault 😅 )

**Comment by edouard-lopez** [comment]
@sohex @filipebarros
`fish-kude-prompt` does have a [caching mechanism](https://github.com/aluxian/fish-kube-prompt#speed) for speed reason, but…

`fish_right_prompt` is correctly executed on every new display, as demonstrated by updating `fish_right_prompt.fish` to:

	function fish_right_prompt	
	    set foo (date '+%N')
	    printf "%s" $foo
	end
	
Our problem comes from `$pure_right_prompt` not being re-evaluated.

**Comment by edouard-lopez** [comment]
see #187

**Comment by schrodincat** [comment]
Fixed in 2.2.0
