### ISSUE TITLE
[Feature Request] show exit code on error

### ISSUE THREAD

**Issue by akkk33** [rafaelrinaldi/pure#188]
Thanks very much for this beautiful work.
I just want to propose a small change, Instead of showing only red `❯` , Just add a number which refers to exit code from previous command on error only.
So it would be like `1❯`.

**Comment by edouard-lopez** [comment]
Hello @akkk33,
You could achieve this by editing [fish_prompt.fish](https://github.com/rafaelrinaldi/pure/blob/47ebc495f5c73be556c041d1f6afc0648c26e9d9/fish_prompt.fish#L7)† and use our `$exit_code` variable:

```diff
-echo -e -n (_pure_prompt $exit_code)
+echo -e -n $exit_code (_pure_prompt $exit_code)
```

†: `$HOME/.config/fish/functions/fish_prompt.fish.fish`

**Comment by akkk33** [comment]
Problem solved, thanks.
