### ISSUE TITLE
More robust shortening algorithm

### ISSUE THREAD

**Issue by andreiborisov** [rafaelrinaldi/pure#198]
Related to https://github.com/rafaelrinaldi/pure/issues/166 I open the discussion on how we should prioritize the prompt components in the shortening function.

Right now we only truncate the path part of the prompt using built-in fish `prompt_pwd` function.

At the very least, we need to truncate Git branch name if it's too long to fix https://github.com/rafaelrinaldi/pure/issues/166. However, I'm not sure, what logic we should use for it. We also can write our own path shortening algorithm.

**Comment by edouard-lopez** [comment]
will deal about that in #166
