### ISSUE TITLE
No colors after upgrade to 2.4.2

### ISSUE THREAD

**Issue by filipebarros** [rafaelrinaldi/pure#200]
After upgrading the package to 2.4.2 (using fisher) and restarting the terminal, all colors in the theme are gone. Terminal colors still work though.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/748089/70993194-62694880-20c3-11ea-821c-f0bc3363a097.png">

## Env

**Pure**

    2.4.2

**Fish**

    3.0.2

**OS/distribution**

    macOS

**Comment by filipebarros** [comment]
locked version to 2.4.1 using fisher and then upgraded again and all seems fine 🤔 

Closing

**Comment by alexmspina** [comment]
I am also experiencing this issue when installing with fisher during a Dockerfile build.

# fish_variables 

<img width="605" alt="image" src="https://user-images.githubusercontent.com/29784275/71302639-b8681580-237b-11ea-804a-01626e761946.png">


# Env

**Pure**
`2.4.2`

**Fish**
`3.0.2`

**OS/distribution**
`golang:alpine3.10`

**Dockerfile**
```
FROM golang:alpine3.10
#
## Configure apt and install packages with DEBIAN_FRONTEND flag to Avoid warnings by switching to noninteractive
RUN apk add --update build-base \
    git \
    fish \
    curl \
    neovim \
    clang \
    protobuf
#
## change the default shell
ENV SHELL /usr/bin/fish
#
## Install fisher
RUN curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
#
## Install Vim Plug for plugin management
RUN curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
#
## install z and pure prompt
RUN /usr/bin/fish -c "fisher add jethrokuan/z rafaelrinaldi/pure"
#
## Install gRPC golang dependencies
RUN go get -u google.golang.org/grpc \
    github.com/golang/protobuf/protoc-gen-go
#
## Install mage
RUN go get -u -d github.com/magefile/mage
#
## Change to magefile directory to install mage command
WORKDIR $GOPATH/src/github.com/magefile/mage
#
## Change to magefile directory to install mage command
RUN go run bootstrap.go
#
##
WORKDIR /root
#
## start z shell
ENTRYPOINT [ "/usr/bin/fish" ]
```

**Comment by schrodincat** [comment]
It seems the issues is `set_color` returns nothing for base terminal colors due to being non-interactive. I’ll add a workaround for this in the next release.

@filipebarros, @alexmspina thanks for reporting!☺️
