### ISSUE TITLE
Transient prompt

### ISSUE THREAD

**Issue by cole-h** [rafaelrinaldi/pure#206]
Is there any interest in implementing a transient prompt similar to [that of Powerlevel10k](https://github.com/romkatv/powerlevel10k/#transient-prompt)?

I haven't looked at any of its code, so I don't know if it would actually be possible or easy to implement in `fish`, but it would save a little bit of space and look nice, IMO.

**Comment by edouard-lopez** [comment]
@faho does that sound feasible to you?

https://github.com/rafaelrinaldi/pure/blob/ec5a708712d453e2305fd4b987a4846d9781c1d8/functions/fish_prompt.fish#L1-L11

**Comment by faho** [comment]
Not without support from fish itself, nno.

**Comment by edouard-lopez** [comment]
Thanks, I'm closing then

**Comment by edouard-lopez** [comment]
@cole-h could #65 be an alternative to your request?

**Comment by euglevi** [comment]
Could it be time to go back to this idea now that fish has some support for it?

**Comment by edouard-lopez** [comment]
Could you please elaborate on what behaviour you expect? This will help for the test

**Comment by euglevi** [comment]
First of all, I am sorry that I know very little about fish scripting so I cannot help. I was thinking at [powerlevel10k](https://github.com/romkatv/powerlevel10k) kind of behaviour.  I am not sure, but it seems that now this should be feasible for fish [see #8412 in Fish repository](https://github.com/fish-shell/fish-shell/pull/8142).

**Comment by edouard-lopez** [comment]
Working on the feature I discovered @zzhaolei's project https://github.com/zzhaolei/transient.fish
