### ISSUE TITLE
Unreadable color

### ISSUE THREAD

**Issue by stefanfrede** [rafaelrinaldi/pure#208]
## Env

**Pure**

2.5.2

**Fish**

3.0.2

**OS/distribution**

macOS 10.15.3

I try to figure out which color setting is responsible for the following color:
<img src="https://i.postimg.cc/KzTdcbYm/Screenshot-2020-02-12-at-10-29-05.png" alt="">
(the color of `vim` in the image).

It is not very readable and I'm a bit lost where to change it.

Thanks!

**Comment by schrodincat** [comment]
@stefanfrede that color isn't controlled by prompt. You can tweak fish colors in the web interface by typing
```
fish_config
```
This particular color is saved in `fish_color_command` variable, check out [fish docs](https://fishshell.com/docs/current/index.html#variables-color) for more info.
