### ISSUE TITLE
Add support for showing mercurial branch name

### ISSUE THREAD

**Issue by jisuoqing** [rafaelrinaldi/pure#21]
First of all, I enjoy this theme so much for my fish shell!

I'm just wondering whether it is possible to show mercurial branch name in addition to git?

Thanks!

**Comment by oranja** [comment]
It should be very easy to implement with @derekstavis's [vcs] plugin.
But... It requires Oh-My-Fish if I recall correctly.

[vcs]: https://github.com/oh-my-fish/plugin-vcs

**Comment by jisuoqing** [comment]
I also saw this, but OMF is down for several days already... Now I just install pure theme manually.

**Comment by bucaran** [comment]
> But... It requires Oh-My-Fish if I recall correctly.

No, it doesn't. `vcs` works with [Fisherman](https://github.com/fisherman/fisherman) too.

```fish
fisher install legacy omf/plugin-vcs
```

**Comment by bucaran** [comment]
@jisuoqing

**Comment by jisuoqing** [comment]
Well, the install log says:

```
Installing (1 of 2) >> legacy
Installing (2 of 2) >> vas
source: Error encountered while sourcing file '/Users/jisuoqing/.config/fisherman/conf.d/functions/git/vcs.git.present.fish':
source: No such file or directory
source: Error encountered while sourcing file '/Users/jisuoqing/.config/fisherman/conf.d/functions/hg/vcs.hg.present.fish':
source: No such file or directory
source: Error encountered while sourcing file '/Users/jisuoqing/.config/fisherman/conf.d/functions/svn/vcs.svn.present.fish':
source: No such file or directory
fish: Unknown command 'autoload'
~/.config/fisherman/conf.d/vcs.init.fish (line 1): autoload -e $path/functions/{git,hg,svn}
                                                   ^
in function '_vcs.pwd'
	called on line 13 of file ~/.config/fisherman/conf.d/vcs.init.fish

in function 'init'
	called on line 1 of file ~/.config/fisherman/conf.d/vcs.init.fish
	with parameter list '/Users/jisuoqing/.config/fisherman/conf.d'

in event handler: handler for generic event 'init_vs'

fish: Unknown command 'vs.name'
~/.config/fisherman/conf.d/vcs.init.fish (line 1): vcs.name
                                                   ^
in command substitution
	called on line 4 of file ~/.config/fisherman/conf.d/vcs.init.fish

in function '_vcs.pwd'
	called on line 13 of file ~/.config/fisherman/conf.d/vcs.init.fish

in function 'init'
	called on line 1 of file ~/.config/fisherman/conf.d/vcs.init.fish
	with parameter list '/Users/jisuoqing/.config/fisherman/conf.d'

in event handler: handler for generic event 'init_vs'

Aye! 2 plugin/s installed in 0s
```

And the error `fish: Unknown command 'autoload'` was given when `cd` to some directory at anytime. Maybe I should report this to fisherman?

**Comment by bucaran** [comment]
@jisuoqing 

**I am really sorry about that!**

> ~~`vcs` works with [Fisherman](https://github.com/fisherman/fisherman) too.~~

@oranja was correct after all. I didn't notice that `vcs` uses `autoload` which I still don't know whether I want to support or not. Just looking at that function makes me cringe! :laughing:

**Comment by derekstavis** [comment]
@jisuoqing `vcs` isn't designed for fisherman.

**Comment by rafaelrinaldi** [comment]
@jisuoqing I'm more than happy to add this as a default feature and would like to stay away from plugins and frameworks if possible. Would you like to go ahead and open a PR?

**Comment by jisuoqing** [comment]
@rafaelrinaldi I believe that would be very nice! However I'm not familiar with shell script...

**Comment by rafaelrinaldi** [comment]
@jisuoqing No worries, thanks for your suggestion nonetheless. Will keep this issue open until its implemented :+1:

**Comment by jisuoqing** [comment]
@rafaelrinaldi Great -- it would be nice to have this work without external plugins or frameworks. Thank all of you for bring up such a fantastic theme!

**Comment by rafaelrinaldi** [comment]
@jisuoqing Thanks for your suggestion but since it has been a year already and we still don't have any PRs in place for this, I'm going to close the issue. Feel free to submit a PR anytime 👍
