### ISSUE TITLE
[Question] How can I change the commands/keywords/characters colors?

### ISSUE THREAD

**Issue by cristianovitorino** [rafaelrinaldi/pure#210]
Hello! Thanks so much for your awesome work on this theme, loving it so far! I have one question:

How can I change the commands/keywords/characters colors? I've messed around and ended up with a nice customization of colors, symbols, etc, but I couldn't figure out how to change the commands/keywords/characters like the in the first screenshot from this project page.

**What I have**
Example: the "sleep 15s; false" commands/keywords/characters.
![fish](https://user-images.githubusercontent.com/57003922/76684133-1f4a4300-65e8-11ea-81b2-d6b357f98fd1.png)

**What I want**
Pure project example screenshot with cream, cyan and light purple commands/keywords/characters.
![68747470733a2f2f692e696d6775722e636f6d2f424878556f68522e706e67 (1)](https://user-images.githubusercontent.com/57003922/76684077-ab0f9f80-65e7-11ea-9296-3e5bce88009c.png)

Changing the terminal theme also doesn't affect anything.

---

## Env

**Pure**

    2.4.2

**Fish**

    fish, version 3.1.0

**OS/distribution**
```
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```

**Comment by cristianovitorino** [comment]
I've found the solution. Just `fish_config colors` on a terminal and customize away : D

**Comment by schrodincat** [comment]
@cristianovitorino how did you get a fish in the prompt on the screenshot?😀

**Comment by cristianovitorino** [comment]
> @cristianovitorino how do you get a fish in the prompt like on your screenshot?

[Font Awesome!](https://fontawesome.com/icons/fish?style=solid) :smile:
