### ISSUE TITLE
Using reverse prompt with vi mode doesn't work as expected

### ISSUE THREAD

**Issue by FraserEmbrey** [rafaelrinaldi/pure#212]
The prompt will remain the same unless I run something like autocomplete.

This makes the reverse prompt kind of pointless for me as it doesn't actually tell me what mode I am in, only what mode I was in when I last refreshed the prompt. I assume that the prompt should refresh itself when I change mode.

## Env

**Pure**

   2.5.2

**Fish**

    fish, version 3.1.0

**Terminal Emulator**

  iTerm2, v3.3.9

**OS/distribution**

    macOS 10.15.4

**Comment by NovaDev94** [comment]
@FraserEmbrey Can you try running these 2 commands?

```
> bind -M insert \e
> bind i
```

They should show
```
bind --preset -M insert \e 'if commandline -P; commandline -f cancel; else; set fish_bind_mode default; commandline -f backward-char repaint-mode; end'

bind --preset -m insert i repaint-mode
```

**Comment by FraserEmbrey** [comment]
Yes, this was my output when running them:

```
bind --preset -M insert \e 'if commandline -P; commandline -f cancel; else; set fish_bind_mode default; commandline -f backward-char repaint-mode; end'
bind --preset -m insert i repaint-mode
```

**Comment by edouard-lopez** [comment]
@FraserEmbrey Is this still and issue?

**Comment by FraserEmbrey** [comment]
This had been working more reliably, I think the issue is resolved and it was only ever present on my mac.
To be honest I have recently been using starship as my prompt.
