### ISSUE TITLE
Weird behavior with git in VS Code

### ISSUE THREAD

**Issue by otaviomad** [rafaelrinaldi/pure#216]
## Env

**Pure**

    2.5.2

**Fish**

    fish, version 3.1.0

**OS/distribution**

    Distributor ID:	Ubuntu
Description:	Ubuntu Focal Fossa (development branch)
Release:	20.04
Codename:	focal

Fish works fine on the terminal but when I open a project in the VS Code terminal I get the following:
`Failed to execute process '/usr/bin/git'. Reason:
The total size of the argument and environment lists 1.5MB exceeds the operating system limit of 2MB.
Try running the command again with fewer arguments.`

This gets printed out multiple times each time I run a command.

**Comment by edouard-lopez** [comment]
Do you still have the issue?
Error message is weird and I find nothing similar online.

**Comment by otaviomad** [comment]
I managed to fix it by removing a few exports that I was no longer using on .fishrc. Though, I must say, I ended up migrating to zsh as it is POSIX compliant and easier to work with.

**Comment by edouard-lopez** [comment]
Thanks @otaviomad :heart:
