### ISSUE TITLE
Add support to Stash indicator (zsh feature)

### ISSUE THREAD

**Issue by Arelav** [rafaelrinaldi/pure#218]
Can be git stash symbol `≡` supported like in ZSH version?
Please.

**Comment by edouard-lopez** [comment]
Nice catch! :clap: 

You can follow what we did with `pure_symbol_git_dirty`:

1. write some [fixtures](https://github.com/rafaelrinaldi/pure/blob/master/tests/fixtures/) and tests [./tests/_pure_prompt_git_dirty.fish.test.fish](https://github.com/rafaelrinaldi/pure/blob/master/tests/_pure_prompt_git_dirty.fish.test.fish)
1. add a config variable `pure_symbol_git_dirty` in [conf.d/pure.fish](https://github.com/rafaelrinaldi/pure/blob/master/conf.d/pure.fish) and [test it](https://github.com/rafaelrinaldi/pure/blob/master/tests/_pure.test.fish#L41
)
	```diff
	+ _pure_set_default pure_symbol_git_stash "≡"
	```
1. implement the function [functions/_pure_prompt_git_dirty.fish.fish](https://github.com/rafaelrinaldi/pure/blob/master/functions/_pure_prompt_git_dirty.fish.fish)
1. update the [documentation](https://github.com/rafaelrinaldi/pure/blob/master/README.md)

For reference: Zsh implementation https://github.com/sindresorhus/pure/blob/81dd496eb380aa051494f93fd99322ec796ec4c2/pure.zsh#L153-L156

Would you mind proposing a pull-request ?

**Comment by Arelav** [comment]
Great news. Thank you!

**Comment by Arelav** [comment]
Please see my attempt. However, it's not ready and my experience is not enough to finish without help.
https://github.com/rafaelrinaldi/pure/pull/222

**Comment by Arelav** [comment]
I'm not Fish shell guru. Looks like nobody interested. Closing this by inactivity.

**Comment by edouard-lopez** [comment]
I will look into merging this issue in the coming days

**Comment by Arelav** [comment]
👏
