### ISSUE TITLE
I ended up with blue text, why not white as expected?

### ISSUE THREAD

**Issue by hisnawi** [rafaelrinaldi/pure#220]
After installing the pure theme I got the text in blue:
![image](https://user-images.githubusercontent.com/8878871/80854685-06750b80-8bef-11ea-9bd9-89e0ac190134.png)

How do I go back to having normal text be white? In the example above the "ls".

This is what I see:
![image](https://user-images.githubusercontent.com/8878871/80854969-64a2ee00-8bf1-11ea-8e71-45e95f70a711.png)

And this is how the actual theme should look like:
![image](https://user-images.githubusercontent.com/8878871/80854974-74223700-8bf1-11ea-8e31-50bf7be9350d.png)

**Comment by schrodincat** [comment]
@hisnawi syntax highlighting controlled by special fish variables. Run `fish_config` to choose one of the predefined themes. When it comes to the white color, in particular, I think it was the default value before fish 3.0.

**Comment by schrodincat** [comment]
@hisnawi here are fish defaults prior to fish 3.0:

```
set -U fish_color_autosuggestion '555' 'brblack'
set -U fish_color_cancel '-r'
set -U fish_color_command '--bold'
set -U fish_color_comment red
set -U fish_color_cwd green
set -U fish_color_cwd_root red
set -U fish_color_end brmagenta
set -U fish_color_error brred
set -U fish_color_escape 'bryellow' '--bold'
set -U fish_color_history_current '--bold'
set -U fish_color_host normal
set -U fish_color_host_remote yellow
set -U fish_color_match '--background=brblue'
set -U fish_color_normal normal
set -U fish_color_operator bryellow
set -U fish_color_param cyan
set -U fish_color_quote yellow
set -U fish_color_redirection brblue
set -U fish_color_search_match 'bryellow' '--background=brblack'
set -U fish_color_selection 'white' '--bold' '--background=brblack'
set -U fish_color_status red
set -U fish_color_user brgreen
set -U fish_color_valid_path '--underline'
```

**Comment by hisnawi** [comment]
Thanks. Now it make sense.
