### ISSUE TITLE
Vi mode reverse symbol not working with hybrid mode

### ISSUE THREAD

**Issue by hisnawi** [rafaelrinaldi/pure#221]
I am utilizing the code from this page, to use hybrid mode behavior between emacs and vi:

#https://fishshell.com/docs/current/#syntax-highlighting

```fish
function hybrid_bindings --description "Vi-style bindings that inherit emacs-style bindings in all modes"
for mode in default insert visual
fish_default_key_bindings -M $mode
end
fish_vi_key_bindings --no-erase
end
set -g fish_key_bindings hybrid_bindings
```

However, the prompt symbol stopped reversing on Vi normal mode.
Is there a way to fix this?

**Comment by edouard-lopez** [comment]
@hisnawi did you find a solution?

**Comment by hisnawi** [comment]
I just disabled the feature altogether.

**Comment by edouard-lopez** [comment]
I'm closing then, feel free to reopen if you want to work on it.
