### ISSUE TITLE
issues with cmd+k and ctrl+c

### ISSUE THREAD

**Issue by caarlos0** [rafaelrinaldi/pure#223]
## Env

**Pure**

    echo $pure_version
    2.5.2

**Fish**

    fish --version
    fish, version 3.1.2

**OS/distribution**

    lsb_release -a
    macOS 10.15.5

---

- when I press ctrl+c while typing a command, the next new line is not shown
- ctrl+l works fine, but cmd+k eats the first line of the prompt

I recorded a gif to show how it looks like:
https://img.carlosbecker.dev/Screen%20Recording%202020-06-29%20at%202.05.17%20PM.gif

Thanks for the great project btw 🙏

**Comment by edouard-lopez** [comment]
@caarlos0 same issue as #157, please see upstream fix.
