### ISSUE TITLE
Drop fundle support

### ISSUE THREAD

**Issue by edouard-lopez** [rafaelrinaldi/pure#231]
Fundle is too time consuming to maintain and inactive for almost 2 years.

So I'm going to remove tests, documentation for it and do not plan to support related issues.

What do you think?

**Comment by nesl247** [comment]
There's really nothing to support other than make sure you use the proper directories for fish. Outside of that, there is literally nothing to do. Not officially supporting it is still fine as a fundle user.

**Comment by edouard-lopez** [comment]
@nesl247 Thanks for your feedback 

The code related to it I found was a test suite but commented. So no reason to pretend we support it when we have no automated way to back this statement. 
Moreover, I prefer to focus my energy on `fisher` support as it's active and widely used in the community. 
Note, the file structure to comply with `fundle` is still there but no guaranty it will work in the future so I prefer to explicitly state there is no official support.

**Comment by nesl247** [comment]
@edouard-lopez Exactly. That's why I meant it's still fine as a fundle user. Fundle is really just a mechanism for downloading/updating/loading, and not really much else. Which is why it doesn't have a lot of activity, it's just not needed.

**Comment by edouard-lopez** [comment]
I manage to fix the failing test  related to `fundle` install  in #227. 
So it's still live for now! :tada:
