### ISSUE TITLE
Source error when installing with fisher

### ISSUE THREAD

**Issue by externl** [rafaelrinaldi/pure#245]
## Env

**Fish**

```
❯ fish --version
fish, version 3.1.2
```

**OS/distribution**

    macOS 11.1

**Fisher output**
```
fisher install version 4.1.0
Fetching https://codeload.github.com/rafaelrinaldi/pure/tar.gz/HEAD
Installing rafaelrinaldi/pure
           /Users/joe/.config/fish/functions/_pure_check_for_new_release.fish
           /Users/joe/.config/fish/functions/_pure_format_time.fish
           /Users/joe/.config/fish/functions/_pure_get_prompt_symbol.fish
           /Users/joe/.config/fish/functions/_pure_parse_directory.fish
           /Users/joe/.config/fish/functions/_pure_parse_git_branch.fish
           /Users/joe/.config/fish/functions/_pure_place_iterm2_prompt_mark.fish
           /Users/joe/.config/fish/functions/_pure_print_prompt.fish
           /Users/joe/.config/fish/functions/_pure_prompt.fish
           /Users/joe/.config/fish/functions/_pure_prompt_beginning.fish
           /Users/joe/.config/fish/functions/_pure_prompt_command_duration.fish
           /Users/joe/.config/fish/functions/_pure_prompt_current_folder.fish
           /Users/joe/.config/fish/functions/_pure_prompt_ending.fish
           /Users/joe/.config/fish/functions/_pure_prompt_first_line.fish
           /Users/joe/.config/fish/functions/_pure_prompt_git.fish
           /Users/joe/.config/fish/functions/_pure_prompt_git_branch.fish
           /Users/joe/.config/fish/functions/_pure_prompt_git_dirty.fish
           /Users/joe/.config/fish/functions/_pure_prompt_git_pending_commits.fish
           /Users/joe/.config/fish/functions/_pure_prompt_git_stash.fish
           /Users/joe/.config/fish/functions/_pure_prompt_jobs.fish
           /Users/joe/.config/fish/functions/_pure_prompt_new_line.fish
           /Users/joe/.config/fish/functions/_pure_prompt_ssh.fish
           /Users/joe/.config/fish/functions/_pure_prompt_ssh_host.fish
           /Users/joe/.config/fish/functions/_pure_prompt_ssh_separator.fish
           /Users/joe/.config/fish/functions/_pure_prompt_ssh_user.fish
           /Users/joe/.config/fish/functions/_pure_prompt_symbol.fish
           /Users/joe/.config/fish/functions/_pure_prompt_system_time.fish
           /Users/joe/.config/fish/functions/_pure_prompt_vimode.fish
           /Users/joe/.config/fish/functions/_pure_prompt_virtualenv.fish
           /Users/joe/.config/fish/functions/_pure_set_color.fish
           /Users/joe/.config/fish/functions/_pure_set_default.fish
           /Users/joe/.config/fish/functions/_pure_string_width.fish
           /Users/joe/.config/fish/functions/_pure_uninstall.fish
           /Users/joe/.config/fish/functions/fish_greeting.fish
           /Users/joe/.config/fish/functions/fish_mode_prompt.fish
           /Users/joe/.config/fish/functions/fish_prompt.fish
           /Users/joe/.config/fish/functions/fish_title.fish
           /Users/joe/.config/fish/conf.d/_pure_init.fish
           /Users/joe/.config/fish/conf.d/pure.fish
source: Error encountered while sourcing file './functions/_pure_uninstall.fish':
source: No such file or directory
Installed 1 plugin/s
```

**Comment by anthonyjclark** [comment]
I just ran into the same issue when installing manually. It appears to be due to [this commit](https://github.com/rafaelrinaldi/pure/commit/3090c67b600cad81d62f0a51e18cc46422277a87) @edouard-lopez

**Comment by sgade** [comment]
Seems unrelated to any manager. Having the same problem after updating using fundle.
Removed the line as a workaround.

**Comment by edouard-lopez** [comment]
Apologies,
I will have a look tonight, in the meantime you can install the previous version:

    fisher install rafaelrinaldi/pure@v3.3.1

**Comment by edouard-lopez** [comment]
Fixed in [`v3.3.3`](https://github.com/rafaelrinaldi/pure/releases/tag/v3.3.3):

    fisher install rafaelrinaldi/pure

**Comment by jorgebucaran** [comment]
@edouard-lopez Why extract the event handler https://github.com/rafaelrinaldi/pure/commit/3090c67b600cad81d62f0a51e18cc46422277a87#diff-0728e51023b9a9b70caf9b61545c9996c007bd0cd70479a4b6be89d5069bc0c2R10? Seems unnecessary and roundabout. I'd just keep it in the snippet.

**Comment by jorgebucaran** [comment]
@edouard-lopez Why extract the event handler https://github.com/rafaelrinaldi/pure/commit/3090c67b600cad81d62f0a51e18cc46422277a87#diff-0728e51023b9a9b70caf9b61545c9996c007bd0cd70479a4b6be89d5069bc0c2R10? Seems unnecessary and roundabout. I'd just keep it in the snippet and put code in the uninstaller to erase the function, but I guess it's up to you.

**Comment by jorgebucaran** [comment]
I prefer `pure_uninstall`, etc., as originally introduced in my PR (https://github.com/rafaelrinaldi/pure/pull/243). Extracting the function into `functions/` and hardcode-sourcing it in `conf.d/_pure_init.fish` is fragile and would break if Fisher changes the `cp` order (unlikely, though) or Pure users customize their `$fisher_path` (more likely). The problem is assuming Pure is installed to `$__fish_config_dir`.

The safe and generic way to avoid these caveats is to handle events as originally introduced in https://github.com/rafaelrinaldi/pure/commit/ba468eb821f140645dc44dddde8d0811c304cf2a.

**Comment by edouard-lopez** [comment]
Thanks @jorgebucaran, I will see what feedback I get on this to prioritize this modification

**Comment by sgade** [comment]
+1 on @jorgebucaran's suggestion. I know [fundle is not supported](https://github.com/rafaelrinaldi/pure/issues/231) but it underlines that the assumed install directory may not be correct (`~/.config/fish/fundle/rafaelrinaldi/pure` in my case).

**Comment by mattmc3** [comment]
https://github.com/rafaelrinaldi/pure/pull/251
