### ISSUE TITLE
Fisher update fails

### ISSUE THREAD

**Issue by edouard-lopez** [rafaelrinaldi/pure#25]
I tried to update using

    $ fisher update pure

And got:

```
Updating >> pure
fish: Unknown command '__fisher_path_update /home/elopez/.config/fisherman/cache/pure'
fish: ;__fisher_path_update /home/elopez/.config/fisherman/cache/pure
       ^
No plugins were updated.
```

@bucaran Should we add a `__fisher_path_update` function that alias to our _installer.fish_ `install_pure` function?

**Comment by bucaran** [comment]
@edouard-lopez It seems you are using an older version of Fisherman. Can you update and try again?

**Comment by bucaran** [comment]
> Should we add a __fisher_path_update function that alias to our installer.fish install_pure function?

I am not sure what `installer.fish` does, but I don't think so. If Fisherman fails to update `pure`, then this is Fisherman's fault right?

**Comment by bucaran** [comment]
<img width="246" alt="screen shot 2016-03-16 at 7 43 08 pm" src="https://cloud.githubusercontent.com/assets/8317250/13809700/55692f9e-ebaf-11e5-823f-f75ff78bc484.png">

**Comment by rafaelrinaldi** [comment]
@edouard-lopez Is this a Fisherman specific issue?

**Comment by bucaran** [comment]
@rafaelrinaldi It's not. @edouard-lopez Let's move the discussion to Fisherman or to the slack channel http://join.fisherman.sh please.

**Comment by rafaelrinaldi** [comment]
@bucaran I just asked because I like to organize issues by tagging them and we have a Fisherman tag. Chill.

**Comment by bucaran** [comment]
Ah, alright.

**Comment by edouard-lopez** [comment]
@bucaran got 

```
$ fisher --version
fisher version 0.7.0
```

**Comment by bucaran** [comment]
@edouard-lopez Good old days. Yeah, you need to upgrade, we are 1.3.1 now, and 1.4.0 is already in the oven.

**Comment by edouard-lopez** [comment]
Fisherman version was indeed problematic. Solved it as follow:

1. after running fisherman/fisherman#162 solution ;
2. run update again:

    ```
    $ fisher update pure
    Updating plugins...
    ▸ pure
    1 plugin/s updated in 6s
    ```
