### ISSUE TITLE
Pure assumes it will be installed in ~/.config/fish and errors when it's not

### ISSUE THREAD

**Issue by mattmc3** [rafaelrinaldi/pure#250]
## Env

**Pure**

    3.3.0

**Fish**

    fish, version 3.1.2

**OS/distribution**

    macOS Big Sur 11.1

Error received when loading Pure without using Fisher/OMF/Fundle

```
source: Error encountered while sourcing file '/Users/mattmc3/.config/fish/functions/_pure_uninstall.fish':
source: No such file or directory
```

Reason for error:

I believe Pure is assuming that it will be installed in my ~/.config/fish directory, but I am instead sourcing it from an alternative location by adding its functions and completions to `$fish_function_path` and `$fish_complete_path`.

Proposed fix:

[This line](https://github.com/rafaelrinaldi/pure/blob/4f217d57b0f4173f67651c6ca4333e11112ad002/conf.d/_pure_init.fish#L10) is the culprit:

```fish
# conf.d/_pure_init.fish
# bad assumption that $__fish_config_dir is where Pure will live
source $__fish_config_dir/functions/_pure_uninstall.fish
```

It could be changed to something like this:

```fish
source (realpath (status --current-filename)/../../functions/_pure_uninstall.fish)
```

**Comment by jorgebucaran** [comment]
Yep, see also https://github.com/rafaelrinaldi/pure/issues/245#issuecomment-745756246
