### ISSUE TITLE
Setting defaults through ~/.config/fish/fish.config not working

### ISSUE THREAD

**Issue by tharindus609** [rafaelrinaldi/pure#252]
## Env

**Pure**

    echo $pure_version
    3.3.5

**Fish**

    fish --version
    fish, version 3.1.2

**OS/distribution**

    uname -a
    Darwin olympus.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101 arm64

~/.config/fish
❯ cat config.fish
_pure_set_default pure_separate_prompt_on_error true
_pure_set_default pure_threshold_command_duration 5
_pure_set_default pure_show_system_time true⏎

~/.config/fish
❯ fish
~/.config/fish
❯

~/.config/fish
❯

~/.config/fish
❯ set --universal pure_show_system_time true

~/.config/fish
21:12:32 ❯

**Comment by tharindus609** [comment]
a restart fixed it i checked everything for almost 3 hours to figure this out

**Comment by jorgebucaran** [comment]
@tharindus609 So, if I understand this right, you opened your `config.fish` file and set some Pure variables. Then you close the file and expected changes to apply to your prompt automatically? Is that correct?

**Comment by jorgebucaran** [comment]
@tharindus609 So, if I understand this right, you opened your `config.fish` file and set some Pure variables. Then closed the file and expected changes to apply to your prompt ¥automatically? Is that correct?

**Comment by edouard-lopez** [comment]
@tharindus609 thanks for the feedback, I believe the README need some live especially the part about customization.
In your case it's related to how universal variables, the order in which [configuration files are initialized](https://fishshell.com/docs/current/index.html#initialization-files) and how we leverage both via our [conf.d/pure.fish](https://github.com/rafaelrinaldi/pure/blob/master/conf.d/pure.fish)

**Comment by tharindus609** [comment]
@jorgebucaran once i added configs to the file i reloaded the fish session. i tried just running fish command and also tried closing my terminal and starting again none seem to work

@edouard-lopez i assumed that ~/.config/fish/config.fish is sourced each time a new fish session is started similar to .bashrc am i wrong to assume that?

**Comment by jorgebucaran** [comment]
@tharindus609 You are not wrong, that's exactly what happens.
