### ISSUE TITLE
id: illegal option -- -

### ISSUE THREAD

**Issue by nicktfried** [rafaelrinaldi/pure#258]
Keep receiving the following after every command only when Pure is installed:

`id: illegal option -- -
usage: id [user]
       id -A
       id -F [user]
       id -G [-n] [user]
       id -M
       id -P [user]
       id -g [-nr] [user]
       id -p [user]
       id -u [-nr] [user]
~`

## Env

**Pure**

    3.4.1

**Fish**

    fish, version 3.1.2

**OS/distribution**

    MacOS Big Sur 11.1

**Comment by edouard-lopez** [comment]
Thank for the feedback @nicktfried.

This is due to macOS `id` command missing the long format option. Until I fix this, you can revert to `3.3.5`:

    fisher install rafaelrinaldi/pure@v3.3.5

**Comment by rakyi** [comment]
`fisher install` does not exist in my version of fisher (3.2.11), but `fisher add rafaelrinaldi/pure@v3.3.5` worked.

**Comment by nicktfried** [comment]
> `fisher install` does not exist in my version of fisher (3.2.11), but `fisher add rafaelrinaldi/pure@v3.3.5` worked.

Update fisher to 4.1

**Comment by nicktfried** [comment]
Thanks!

**Comment by edouard-lopez** [comment]
@nicktfried you can install

    fisher install rafaelrinaldi/pure@v3.4.2
