### ISSUE TITLE
Issue with `__parse_current_folder`

### ISSUE THREAD

**Issue by rafaelrinaldi** [rafaelrinaldi/pure#26]
I just did a fresh install and after opening a new Terminal tab I started getting this error:

```
fish: Unknown command '__parse_current_folder'
~/.config/fish/functions/fish_prompt.fish (line 1): __parse_current_folder
                                                    ^
in command substitution
	called on line 28 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input
```

Ping @edouard-lopez

**Comment by rafaelrinaldi** [comment]
@edouard-lopez Doesn't this impact `v1.0.0`?

**Comment by edouard-lopez** [comment]
@rafaelrinaldi which method of install did you used? sorry for the delay been busy.

I'm just discover the [docker-fish image](https://github.com/colstrom/docker-fish) and it might be useful for developing/testing:

```
docker pull colstrom/fish
docker run -it colstrom/fish
```

Then in the docker:

```
apk-install  curl git
curl -Ls https://raw.github.com/rafaelrinaldi/pure/master/installer.fish > /tmp/pure_installer.fish
source /tmp/pure_installer.fish; and install_pure
```

Above command work fine:
```

Installing Pure theme
        Set environment variable: $FISH_CONFIG_DIR
        Set environment variable: $PURE_INSTALL_DIR
        Checking for git availability ✔
        Fetching theme's source ✔
        Backuping existing theme
 ✔
        Enabling autoloading for pure's functions on shell init ✔
        Enabling theme ✔
        Cleaning after install ✔
```

**Comment by rafaelrinaldi** [comment]
@edouard-lopez Nothing to be sorry about :wink: 

Yeah, I just tried the vanilla installer script. Not sure why I got that error...

I will try testing within the Docker container when I have a chance.

**Comment by rafaelrinaldi** [comment]
@edouard-lopez Just did another clean install run and it worked 👍 

![shrug](https://cldup.com/TLrIFoGy2T.gif)

**Comment by rafaelrinaldi** [comment]
@edouard-lopez Nevermind, it happened again. Just didn't happened during install. It seems like it can't find functions because they're installed under `functions/theme-pure` and it will look for `.fish` files under `/functions`. Is there a way to "source" them? I couldn't find any.

Maybe @brj have an idea on how to solve this?

**Comment by brj** [comment]
@rafaelrinaldi I tried in a fresh install, without fisherman, and was able to repro the problem.

One issue could be in `pure::enable_autoloading`

```fish
if not test (grep "$THEME_PURE" $FISH_CONFIG_DIR/config.fish 2>&1 >/dev/null)
        echo "$marker" >> $FISH_CONFIG_DIR/config.fish
        echo "set fish_function_path $PURE_INSTALL_DIR" '$fish_function_path' >> $FISH_CONFIG_DIR/config.fish
    end
```

I don't use a config.fish, so that code above will not write anything to no config.fish, which means, when I start a new session, `$PURE_INSTALL_DIR` will not be set anywhere and fish will not be able to autoload the helper functions you put inside `~/.config/fish/theme-pure`.
