### ISSUE TITLE
Set colors right like on theme screenshots

### ISSUE THREAD

**Issue by stanf0rd** [rafaelrinaldi/pure#270]
Hello and thank you for nice theme!

How can I set fish colors like on main screenshot:
<img width="354" alt="Screenshot 2021-01-09 at 20 20 16" src="https://user-images.githubusercontent.com/28190898/104104225-d884b280-52b7-11eb-9a92-fafdb9f2a22d.png">

After clean install (using fisher) I receive default fish colors (random command sreenshot):
<img width="354" alt="Screenshot 2021-01-09 at 20 20 16" src="https://user-images.githubusercontent.com/28190898/104104273-184b9a00-52b8-11eb-8b6f-811284eb0b1d.png">

I changed background color using terminal app itself, but cannot find info about color scheme :(

**Pure**
    echo $pure_version: `3.5.0`

**Fish**
    fish --version: `3.1.2`

**OS/distribution**
    Mac OS 11.1 Bug Sur

**Terminal app**
    Hyper, 3.0.2
        OR
    Mac OS Terminal, 1.11

**Comment by stanf0rd** [comment]
For example, original zsh Pure theme has description about their screenshots:

> In the screenshot you see Pure running in Hyper with the hyper-snazzy theme and Menlo font.

It would be great to see here something similar :)

**Comment by edouard-lopez** [comment]
The PR explaining the screenshot https://github.com/rafaelrinaldi/pure/pull/132#issuecomment-454493102
You are lucky, I ported the [ayu theme to fish](https://github.com/edouard-lopez/ayu-theme.fish) last week. It's available as a fisher plug-in with 3 variants (light, dark and mirage)

**Comment by stanf0rd** [comment]
Thank you so much!
