### ISSUE TITLE
Support oh-my-fish

### ISSUE THREAD

**Issue by rafaelrinaldi** [rafaelrinaldi/pure#3]
Add support to [`oh-my-fish`](https://github.com/oh-my-fish/oh-my-fish).

**Comment by edouard-lopez** [comment]
What is required to do so?

**Comment by edouard-lopez** [comment]
I asked on the [omf slack](https://oh-my-fish.slack.com/messages/general/) and the git repo need to follow an undocumented convention:

> derekstavis
> 12:32 You have to rename the repositóry
> ​12:32 Should read `theme-pure`

In order for the `omf install <theme>` to work.

**Comment by rafaelrinaldi** [comment]
@edouard-lopez Hey Edouard, thanks for the interest. I've created this issue just as a reminder of a nice-to-have feature. I don't use `oh-my-fish` myself.

If you are willing to create a PR for this, I can help you out.

Thanks!

**Comment by edouard-lopez** [comment]
I submitted a PR to add support for omf

**Comment by rafaelrinaldi** [comment]
@edouard-lopez Thanks for that! I'm going to take a look into it this weekend. I think it's better to create another repo with the contents of `pure` as a submodule, so people relying on this repository (currently `~24`) don't get frustrated. Should work, right?

**Comment by edouard-lopez** [comment]
The merge should be backward-compatible as I just extracted method to own file to follow omf convention and leverage fish lazy loading mechanism. 
Then I can use or update my repo to add yours as a submodule and serve as entry point for the omf theme.

Is it OK with you?

**Comment by edouard-lopez** [comment]
We might not need to have 2 repo as they are [talking to support repo without the `theme-` prefix for 3rd-party theme](https://github.com/oh-my-fish/oh-my-fish/issues/191).

**Comment by rafaelrinaldi** [comment]
@edouard-lopez It's perfectly fine from my side, man. Go ahead :+1:

**Comment by rafaelrinaldi** [comment]
@edouard-lopez I saw your fork and I noticed that you split the functions into separate files. This probably is going to lead to maintenance problems, because every time I change something I will need to make sure your repository is also updated. I can see two solutions:

1. Change my repository to use the same structure as yours.
2. Automate the update process (every time a new release come out I make a pull request on your repository).

Thoughts?

**Comment by edouard-lopez** [comment]
I prefer to keep you as the main repo, so there is a single entry point as you already got the followers and I just adapted the project structure so it is compatible with OMF. It should still work fine for non-OMF users.

So better keep one entry point IMHO. If other changes are needed, I'll fork again and submit PR to you.

**Comment by rafaelrinaldi** [comment]
:+1: Closing the issue then. Thanks for this!

**Comment by bucaran** [comment]
@rafaelrinaldi @edouard-lopez 

Check out [Fisherman](https://github.com/fisherman/fisherman), there you can install any themes or plugins (including OMF) without restrictions.

```fish
fisher install rafaelrinaldi/pure
```

**Comment by rafaelrinaldi** [comment]
@bucaran Nice. That's how I would expect OMF to work as well. Thanks for sharing!

**Comment by bpinto** [comment]
Oh My Fish is the only framework that has full compatibility with fish shell `fish_config`.

When you use fish, you have access to the web config which allows users to use `fish_config` builtin tool.
The way @edouard-lopez broke the one function in several files is also more-fishy as it's a good thing to have one function per file (supports lazy loading).

Perhaps we can merge your work as it was being done on #5 ?

**Comment by rafaelrinaldi** [comment]
@bpinto Thanks for the thoroughly response. I will follow what @edouard-lopez did on [his fork](https://github.com/edouard-lopez/theme-pure) and merge it to the original repository so we can avoid trouble by having a single entry point. Just one question, is it a requirement to prefix the repository name with `theme-`?

**Comment by oranja** [comment]
For now it is a requirement. Without it OMF can't tell that it's a theme and resorts to considering it a regular package (i.e. plugin, which shouldn't be supported as an argument to `omf theme`).
Now OMF also supports `omf-theme-` as a prefix, but seems like this isn't necessarily of interest to you...
Anyway, the final commands will still be `omf install pure` and `omf theme pure`.

**Comment by edouard-lopez** [comment]
There is a discussion about that in oh-my-fish/oh-my-fish#191. But I don't see any progress on the thread.
I'm going to submit a pull request to add the theme (via my repo) to the `oh-my-fish` repo, is it ok with you @rafaelrinaldi ?

**Comment by edouard-lopez** [comment]
I'm going to merge back into your repo

**Comment by rafaelrinaldi** [comment]
@oranja Thanks for explaining. I get it now.

Well, renaming my repository is not a big deal. @edouard-lopez as I've suggested, let's all work together on the same repository. I made you a main contributor so you can do whatever is required. I was going to work on this tonight but if you can do that if you want.

The only thing to keep in mind is that it should work regardless the user uses `omf` or not :+1:

**Comment by bucaran** [comment]
@edouard-lopez If you submit the theme to the OMF organization, there exists a slight chance that it will not be compatible with other systems (fundle, Fisherman, etc), but only slight. 

That is, if the OMF folks play well and don't resort to hostility tactics like in:

* https://github.com/oh-my-fish/oh-my-fish/issues/223

Related:
* https://github.com/oh-my-fish/theme-bobthefish/pull/19

**Comment by edouard-lopez** [comment]
@rafaelrinaldi the doc need to be updated after:

1. your repo is renamed to `theme-pure` with

         omf install https://github.com/rafaelrinaldi/pure.git

2. the repo is added to `omf` theme list with (see #5):

         omf install pure

**Comment by oranja** [comment]
Actually GitHub recently introduced automatic redirects, so you can rename `pure` to `theme-pure` to `omf-theme-pure`, then back to to `pure`, and never care again about OMF's repository naming conventions ;)

**Comment by bucaran** [comment]
> Oh My Fish is the only framework that has full compatibility with fish shell fish_config

The same is true for Fisherman. I don't know about fundle.

**Comment by bpinto** [comment]
We could use the automatic redirects, that's a good idea.

> The same is true for Fisherman.

It's not.

**Comment by bucaran** [comment]
> It's not.

It is, but I'll let you have that feature if you really want. :wink:
