### ISSUE TITLE
Line breaks break the line

### ISSUE THREAD

**Issue by bfred-it** [rafaelrinaldi/pure#31]
Hello! Here's the bug I mentioned on Twitter.

0. I just installed pure via curl
0. I pasted the curl command again
0. I pressed the left arrow key multiple times to go back to the first line
0. I only pressed `.`

![timeupdate](https://cloud.githubusercontent.com/assets/1402241/21017845/92d7f5da-bd1f-11e6-92f3-67faabe55937.gif)

Notice how an extra `f` pops out :(

I'd like to know if it's just me or of it's pure.fish

Also for some reason, Pure doesn't persist. A new window will go back to the old style

**Comment by edouard-lopez** [comment]
Can't replicate on `2.4.0`, which version of `fish` do you use?

Could you try to update if not on the last `fish`?

**Comment by bfred-it** [comment]
It seems that it was related to my other config in `config.fish`

Now the issue is making pure persistent :D 

I installed it with fisher but it still goes away when I open a new window
