### ISSUE TITLE
Make it persistent

### ISSUE THREAD

**Issue by bfred-it** [rafaelrinaldi/pure#32]
I tried installing it via curl and via fisher, but pure is only applied in the current session, it doesn't persist across tabs/windows/sessions.

How do I set it up?

**Comment by edouard-lopez** [comment]
That's weird, could you test on a vanilla environment without other config?

**Comment by rafaelrinaldi** [comment]
@bfred-it Is this still an issue?

**Comment by bfred-it** [comment]
Still an issue, I'll have to try a new environment

**Comment by rafaelrinaldi** [comment]
@bfred-it Is Fish itself persisted across sessions?

**Comment by bfred-it** [comment]
Yes

**Comment by rafaelrinaldi** [comment]
@bfred-it Hm, that's very weird. Let me know once you can reproduce it so I can help you out 👍

**Comment by edouard-lopez** [comment]
Do you [reproduce in Docker](https://github.com/rafaelrinaldi/pure/wiki/Test-in-a-Docker)?

**Comment by bfred-it** [comment]
Solved it. I had this in my `~/.config/fish/config.fish` file, which overrode **pure**'s:

```fish

function fish_prompt
  set last_status $status

  set_color $fish_color_cwd
  printf '%s' (prompt_pwd)
  set_color normal

  printf '%s ' (__fish_git_prompt)

  set_color normal
end
```

I finally figured it out after reinstalling fish, fisherman and after several errors try an empty `config.fish` (I thought I had tried that before)

For personal reference, here's how I reinstalled everything:
```
brew remove fish
fisher self-uninstall

brew install fish
brew tap fisherman/tap
brew install fisherman
fisher rafaelrinaldi/pure
```
