### ISSUE TITLE
Always print CMD_DURATION

### ISSUE THREAD

**Issue by amosbird** [rafaelrinaldi/pure#36]
Is there a configuration that make `pure` to echo `CMD_DURATION` no matter what the ret code is? How can I modify the time threshold?

**Comment by amosbird** [comment]
@edouard-lopez

**Comment by bjorngylling** [comment]
I know this is closed but it seems like the sensible place to ask, why isn't the default behaviour to show the last command execution time always (given it exceeds a threshold)? That is how pure-zsh works after all. I can't see any reason to only show the duration for commands that failed, it makes no sense.

I forked pure-fish and changed this behaviour to be in line with pure-zsh, commit available [here](https://github.com/bjorngylling/pure/commit/8b4444c009db5afa43422967a94b014b6173cecf). I also changed the whitespace between git_dirty and git_arrows from tab to space as well to make it even more similar to pure-zsh.

Here is a screenshot comparing pure-zsh (the first two prompts) with my fork of pure-fish (the last prompt)
<img width="275" alt="screen shot 2017-02-21 at 22 08 39" src="https://cloud.githubusercontent.com/assets/86396/23185178/c1d3ca0a-f882-11e6-9ba4-3aa013e5bcec.png">

**Comment by rafaelrinaldi** [comment]
@bjorngylling Hey, thanks for your suggestion. Our idea here is indeed to be as consistent as possible with the original plugin. Both have an option where you can configure the execution time threshold but you are right, I don't know why we only show it for failed commands. Good catch.

I will open an issue to track this and will mention you 👍 

Just one thing, the tone you have used here doesn't sound friendly at all, as a matter of fact it sounds like a demand. Keep in mind that this project is maintained by actual human beings, on their spare time and for free so try to be a little more polite in the future.

**Comment by bjorngylling** [comment]
I apologise if it came across as hostile or demanding, that was not my intention. It seemed as if the original posters' request got shot down even though it is how it works in pure-zsh. I'd be happy to create a pull request for this if you are interested.

**Comment by rafaelrinaldi** [comment]
@bjorngylling That's quite alright, no problem. I understand that communication over text can be tricky sometimes.

If you feel like opening a PR for that it would be awesome 👍 

Thanks again.

**Comment by edouard-lopez** [comment]
@bjorngylling @amosbird  Sorry if I sounded a bit harsh, it's wasn't my intent to discourage contributors. I reckon the variable was rename from `CMD_DURATION` to [`PURE_CMD_MAX_EXEC_TIME`](https://github.com/sindresorhus/pure#pure_cmd_max_exec_time). 

Feel free to submit a PR so we can improve the situation.

**Comment by edouard-lopez** [comment]
I realize this has been managed in a new issue.

So closing this one in favor of #43.
