### ISSUE TITLE
Broken prompt

### ISSUE THREAD

**Issue by rafaelrinaldi** [rafaelrinaldi/pure#37]
After introducing the prompt customizations on our last release, I think we might have broken something. Just did a fresh install on a new computer via both the default installer script and _Oh My Fish_ and I the prompt is not displaying symbols.

See the screenshot:
<img width="842" alt="screen shot 2017-01-17 at 10 34 07 pm" src="https://cloud.githubusercontent.com/assets/87162/22049985/14fca98e-dd05-11e6-809e-823da3ab0591.png">

- No arrow symbol indicating user input
- No Git hints whatsoever
- No cwd hints
- Colors look different from previous defaults

Can anyone confirm/help? @Shougo @edouard-lopez

**Comment by edouard-lopez** [comment]
I was unable to [reproduce in a Docker environment with a fresh install](https://github.com/rafaelrinaldi/pure/wiki/Test-in-a-Docker):

![selection_055](https://cloud.githubusercontent.com/assets/1212392/22067635/63a078ee-dd92-11e6-9479-9c33c049b582.png)

* The prompt switch from: `root@35baafcaf81b /#` to `❯`
* got `cd` hints ;
* got git status ;
![selection_056](https://cloud.githubusercontent.com/assets/1212392/22067745/dd429c90-dd92-11e6-9668-cf24567882a1.png)

Try removing your config.

**Comment by rafaelrinaldi** [comment]
@edouard-lopez So weird. I removed all my configuration and I still have this weird behavior.

**Comment by edouard-lopez** [comment]
@rafaelrinaldi did you reproduce on the docker ? Might be your terminal application.
Or maybe try to go back in the git history.

**Comment by rafaelrinaldi** [comment]
It was some junk living on my `$HOME`. All good now 👍
