### ISSUE TITLE
Broken after fish update?

### ISSUE THREAD

**Issue by rafaelrinaldi** [rafaelrinaldi/pure#38]
Just updated fish to `2.5.0` today and it seems like prompt is broken (yup, it's me again!). This is what I get:

```
test returned eval errors:
        invalid integer ''
test returned eval errors:
        invalid integer ''
~ 
❯ 
```

Anyone else experiencing the same issue?

**Comment by sagebind** [comment]
This not in the [release notes](https://fishshell.com/release_notes.html) looks to be the problem:

> Like other shells, the test builting now returns an error for numeric operations on invalid integers (#3346, #3581).
