### ISSUE TITLE
test returned eval errors

### ISSUE THREAD

**Issue by attilagyorffy** [rafaelrinaldi/pure#40]
Hi there,

This is an issue that started surfacing after I've upgraded to the latest version (2.5) of fish. I'm using fisher.sh to manage the fish *plugins*.

My guts tell me that there's an issue in the `fish.prompt` code but I'm not a fish expert. This happens every time I run a command:

```
test returned eval errors
```

![screen shot 2017-02-07 at 10 27 39](https://cloud.githubusercontent.com/assets/9091/22685392/73c724e6-ed20-11e6-977a-374a9809c03c.png)

Given that fish does not have a debug mode yet (like bash) I was unable to quickly figure out what actually happens, I'm afraid.

I was also thinking whether this was a regression in fish itself and found this bug:
https://github.com/fish-shell/fish-shell/issues/3753

Having updated to fish HEAD (g162053ed) I was hoping this issue will be sorted but it seems to be outstanding.

Any help would be greatly appreciated, thank you.

PS: I'm on mac OS 10.12.3 (16D32) and am using the built-in Terminal.app

**Comment by edouard-lopez** [comment]
This is fixed by v1.0.1, please update 

    fisher update pure

see #38 for context.

**Comment by attilagyorffy** [comment]
Hmm, I thought I have updated before... Never mind. Reinstalling pure worked. Thank you @edouard-lopez
