### ISSUE TITLE
Username and host not displayed when in an SSH session

### ISSUE THREAD

**Issue by benedictleejh** [rafaelrinaldi/pure#41]
As per the title, the username and host is not displayed when in an SSH session. Just to be sure, I've tried looking through the code, and couldn't find any location where the SSH session is being tested for, and the username and host being displayed.

**Comment by rafaelrinaldi** [comment]
You are right. For some reason I thought this was implemented but we haven't pushed it yet. Will update the readme file so it's not misleading.

Thanks for the report and feel free to open a PR if you want 👍
