### ISSUE TITLE
line break before prompt

### ISSUE THREAD

**Issue by selfagency** [rafaelrinaldi/pure#44]
is there a way to get rid of this line break i'm getting before the prompt?

<img width="230" alt="screenshot 2017-03-03 16 41 05" src="https://cloud.githubusercontent.com/assets/2541728/23569996/3ffaa6a6-0030-11e7-8bbb-1b7fcb6cd255.png">

**Comment by rafaelrinaldi** [comment]
Hum, interesting. Line breaks are only supposed to happen after your first input. Is this weird triangle-shaped character being displayed every time?

**Comment by edouard-lopez** [comment]
@selfagency I got the same behavior in [`zsh-pure`](https://github.com/sindresorhus/pure/blob/master/pure.zsh#L137-L139) so it's the expected behavior.

Anyway, if you want to change it, it comes from the test on [`pure_fresh_session`](https://github.com/rafaelrinaldi/pure/blob/8b4444c009db5afa43422967a94b014b6173cecf/fish_prompt.fish#L48).

**Comment by selfagency** [comment]
the weird triangle is my iterm fish shell integration

**Comment by hutruhup** [comment]
Works fine with item. But it seems there is still compatible issue with hyper.
It has a line break and path before the first input when open a new window, but no problem with new tabs.
![First Open](https://cloud.githubusercontent.com/assets/26748166/24420430/de15db0a-13c0-11e7-9239-6828d12969ab.png)

**Comment by rafaelrinaldi** [comment]
@hutruhup Hum, weird... I have Hyper installed here and it works perfectly. Let me know if you can come up with a consistent way to reproduce this.

**Comment by hutruhup** [comment]
While installing with fisherman, it shows the same as the screenshot. With omf, it doesn't have line break before first input but still have double path.
