### ISSUE TITLE
Work around native fish prompt for long filepaths

### ISSUE THREAD

**Issue by pierrebeaucamp** [rafaelrinaldi/pure#49]
Hey,

I just switched to fish and ran into the issue of it changing my prompt to `>` if the line is really long. This behavior is documented here: https://github.com/fish-shell/fish-shell/issues/904.

As *pure* is a two line prompt, this behavior is not needed. Apparently one can work around this issue by wrapping the first line in a `--on-event fish_prompt` function, as suggested here: https://github.com/fish-shell/fish-shell/issues/904#issuecomment-290882082.

Would it be possible to adjust *pure* accordingly?

Thanks

**Comment by rafaelrinaldi** [comment]
@pierrebeaucamp Thanks for your report. Would you be willing to provide a way to troubleshoot current behavior vs. expected? It's still unclear to me what the expectations are.

You can also submit a PR if you feel like it, I'm happy to provide support 👍

**Comment by pierrebeaucamp** [comment]
Sorry for the late reply. I was actually not sure what the exact behavior was in zsh, so I had to go back and install it again.

Using zsh and pure, once the filepath grows longer / wider than the terminal window, it tries to shorted the filepath to make everything fit. For example, instead of displaying `/home/pierrebeaucamp/code/foo/...` it would display `~/code/foo/...`.

Interestingly enough, if it can't shorten the filepath, it just started displaying 'private' in the path:
![screen shot 2017-04-04 at 13 46 03](https://cloud.githubusercontent.com/assets/3158551/24721062/1cbc58b4-1a0d-11e7-9c42-15ad941c9f51.png)

In fish, it appears that fish ignores everything in `fish_prompt` as soon as it doesn't fit onto the screen anymore. This can be easily replicated if you go to a long filepath and then make your window really narrow. Alternatively, just create a super long path:
![capture](https://cloud.githubusercontent.com/assets/3158551/24721416/4fd0cef0-1a0e-11e7-8ff8-0669584f2072.PNG)

I can look into creating a PR on the weekend.
