### ISSUE TITLE
Display virtualenv in prompt

### ISSUE THREAD

**Issue by andrroy** [rafaelrinaldi/pure#50]
Hi! I've just started using pure, and I'm really liking it so far. The only thing I'm missing, is having my virtualenv show up in my prompt if sourced. Is it possible for me to extend my prompt, so that the name of the virtualenv is added?

**Comment by rafaelrinaldi** [comment]
Hey thanks for your suggestion! I am glad that you find `pure` helpful.

Even though I don't personally take much value by adding this feature I am willing to give it a go if users like it. The only thing that comes to my mind is regarding the behavior for virtual envs on the original ZSH version?

I think this is also a good opportunity to share something I've been thinking about lately... I have been very conservative about making this project 100% compatible with the original version but I am changing my mind. I think we should definitely support all the features but I don't really see problems adding more features on top. What do you think? (cc @edouard-lopez @Shougo @oranja)

<sup>Shout out to @mortevn for #54 :v:</sup>

**Comment by mortenvn** [comment]
> The only thing that comes to my mind is regarding the behavior for virtual envs on the original ZSH version?

@rafaelrinaldi: Actually, this feature has just become part of the original ZSH version as well. I submitted a PR (https://github.com/sindresorhus/pure/pull/325) which has now been merged. 

In other words, merging #54 would just mean supporting another feature from the original theme 😃

**Comment by oranja** [comment]
@rafaelrinaldi I never used zsh, but I respect your principle of staying in synchronization with the source. It justifies the name.
If there's value and desire (yours or anyone else's) to departing from the source and experimenting, the fork is just a click away.

**Comment by edouard-lopez** [comment]
Thanks to @mortnod's PR #54 being merged we can close this one :+1:
