### ISSUE TITLE
Array index out of bounds

### ISSUE THREAD

**Issue by herrbischoff** [rafaelrinaldi/pure#52]
Installing pure via `fundle` on macOS 10.12.4 works as expected. Installing it the same way on a FreeBSD 11 machine does not:

```
 fish -v
fish, version 2.5.0
test: Missing argument at index 2
test: Missing argument at index 2
Array index out of bounds
~/.config/fish/fundle/rafaelrinaldi/pure/__format_time.fish (line 7):   set -l threshold $argv[2]
                                                                                               ^
in function “__format_time”
	called on line 41 of file ~/.config/fish/fundle/rafaelrinaldi/pure/fish_prompt.fish
	with parameter list “5”

in command substitution
	called on line 39 of file ~/.config/fish/fundle/rafaelrinaldi/pure/fish_prompt.fish

in function “fish_prompt”
	called on standard input

in command substitution
	called on standard input

test: Missing argument at index 2
```

Also note the missing `❯`.

This seems to be similar to #47 but I'm already using the latest master of pure and fish 2.5.0, it appears the issue is not fully resolved yet.

**Comment by herrbischoff** [comment]
It turned out to be an issue with fundle, which I have dropped since in favor of manually installing the handful of add-ons I need. Therefore, I'm closing this issue.

**Comment by rafaelrinaldi** [comment]
@herrbischoff Thank you for reporting it. I'm glad it is already solved. Let us know if you find anything wrong with it in the future 👍
