### ISSUE TITLE
Prompt disappears when entering some folders

### ISSUE THREAD

**Issue by heyarne** [rafaelrinaldi/pure#55]
I know this is really vague, but I'd love some help on debugging this: The prompt looks very different when entering some folders. A screenshot might show better what I mean:

![screen shot 2017-07-04 at 17 27 01](https://user-images.githubusercontent.com/525780/27836051-052fc632-60de-11e7-9aec-874fe6b31007.png)
 
The folder contains a git repository, but that alone should not be the reason. I have other git repos that work just fine. I am using fish version 2.6. I am on macOS 10.12.1. If there is any other info I can help with, I'll happily provide it. Thanks in advance!

**Comment by heyarne** [comment]
What's even weirder: I issue `git checkout master` and the prompt reappears in its old glory. The branch name I was on before was `bugfix/filter-is-not-a-function`.

**Comment by oranja** [comment]
This seems like a bug in handling some git repo state.
To get a better idea and to cross out or consider other possibilites, are you using `virtualenv` or something similiar in the directories that fail?
In general, can you point out to anything in common to the repositories that make `pure` fail? submodules? detached heads? branches? remotes? unstaged changes? local unpushed commits?

**Comment by heyarne** [comment]
I do not have a virtualenv in it. The repo does not have submodules, it's not in detached head state, unstaged changes or not don't really make a difference. I'll try to find more cases and I'll try to find some common properties in them.

**Comment by vadikace** [comment]
+1 
Also had the same issue a while ago, if needed would like to assist in fixing it

**Comment by rafaelrinaldi** [comment]
@heyarne Thanks for the report, this behavior does look weird indeed. Please, try to come up with reproducible steps so we can better assist you.

@vadikace You are more than welcome to jump into this issue if you feel like it 👍

**Comment by heyarne** [comment]
I've been able to reproduce the behavior whenever the path + git status exceeds a certain length. I attached some screenshots to clarify what exactly I mean:

<img width="850" alt="screen shot 2018-03-02 at 14 02 49" src="https://user-images.githubusercontent.com/525780/36900183-8e800dc8-1e22-11e8-9e5a-cf36e56d47a1.png">

Terminal at 104x24, length of path + git status: 94 chars

<img width="843" alt="screen shot 2018-03-02 at 14 04 29" src="https://user-images.githubusercontent.com/525780/36900215-afad3ef8-1e22-11e8-8148-097eaf40a902.png">

Terminal at 103x24, length of path + git status: 94 chars (same as above)

<img width="850" alt="screen shot 2018-03-02 at 14 09 00" src="https://user-images.githubusercontent.com/525780/36900372-5bcdee80-1e23-11e8-86ae-d3b179b73354.png">

Terminal at 104x24, length of path + git status: first 94 chars, then 95 chars

<img width="262" alt="screen shot 2018-03-02 at 14 13 32" src="https://user-images.githubusercontent.com/525780/36900535-ed14080c-1e23-11e8-9f4e-d7aa437bb47d.png">

Terminal at 20x11, length of path: 1

<img width="262" alt="screen shot 2018-03-02 at 14 14 24" src="https://user-images.githubusercontent.com/525780/36900563-08ae720a-1e24-11e8-885f-9fac962387b3.png">

Terminal at 20x11, length of path: 10

<img width="269" alt="screen shot 2018-03-02 at 14 15 00" src="https://user-images.githubusercontent.com/525780/36900589-1c9af05e-1e24-11e8-88f8-df5f72e0e332.png">

Terminal at 21x11, length of path: 10

I hope this is clear enough and makes this reproducible. I'm using Terminal.app Version 2.8, macOS 10.13 and fish version 2.7.1.

**Comment by rafaelrinaldi** [comment]
@heyarne Thanks for the details. We will look into it.

@vadikace Still wanna attempt a PR?

**Comment by edouard-lopez** [comment]
I can't reproduce with:

```
❯ cd ~/.config/fisherman/pure/
❯ git log | head -n 1
❯ commit 69c14e0d89b99f61ced5c2ab97d906a533cab3d5
```

```
/tmp 
❯ mkdir -p /tmp/Quo/consequatur/ut/dolore/ducimus/et/vero/soluta./Vel/est/alias/consequatur./Nobis/nisi/voluptatum/libero/suscipit/porro/libero/qui/eaque

/tmp 
❯ cd /tmp/Quo/consequatur/ut/dolore/ducimus/et/vero/soluta./Vel/est/alias/consequatur./Nobis/nisi/voluptatum/libero/suscipit/porro/libero/qui/eaque

/tmp/Quo/consequatur/ut/dolore/ducimus/et/vero/soluta./Vel/est/alias/consequatur./Nobis/nisi/voluptatum/libero/suscipit/porro/libero/qui/eaque 
❯ git init
Initialized empty Git repository in /tmp/Quo/consequatur/ut/dolore/ducimus/et/vero/soluta./Vel/est/alias/consequatur./Nobis/nisi/voluptatum/libero/suscipit/porro/libero/qui/eaque/.git/

/tmp/Quo/consequatur/ut/dolore/ducimus/et/vero/soluta./Vel/est/alias/consequatur./Nobis/nisi/voluptatum/libero/suscipit/porro/libero/qui/eaque master 
❯ echo 'hello world'
hello world

/tmp/Quo/consequatur/ut/dolore/ducimus/et/vero/soluta./Vel/est/alias/consequatur./Nobis/nisi/voluptatum/libero/suscipit/porro/libero/qui/eaque master 
❯ 
```

**Comment by edouard-lopez** [comment]
@heyarne 
I created a [docker image `pure-fish`](https://hub.docker.com/r/edouardlopez/pure-fish/) if you want to try on a clean env.

cc @rafaelrinaldi

**Comment by heyarne** [comment]
Oh wow... this is a bit embarassing. `fisher install pure` doesn't install `rafalrinaldi/pure` but instead pure from [this repo](https://github.com/vkovtash/pure). Indeed, couldn't reproduce the issue after executing `fisher rm pure; fisher install rafaelrinaldi/pure`. I'm going to close this, thanks for the effort and sorry! I assumed there was just one port.

**Comment by edouard-lopez** [comment]
As mentioned in this [`fisherman` issue](https://github.com/fisherman/fisherman/issues/410#issuecomment-370649373), it might be due to a previous install of ` vkovtash/pure` that was cached in the `fishfile`.
