### ISSUE TITLE
Terminal emulator and theme

### ISSUE THREAD

**Issue by gvieira** [rafaelrinaldi/pure#59]
Hi there,

Would you mind telling us which is that beautiful terminal emulator (and theme) from the README.md?

Thanks!
GV

**Comment by gvieira** [comment]
Nevermind! I think I found out: [Hyper](http://hyper.is) and [PaperColor](https://www.npmjs.com/package/hyper-papercolor), am I wrong?

**Comment by rafaelrinaldi** [comment]
@gvieira You are correct 👍
