### ISSUE TITLE
Remove Oh My Fish! framework badge

### ISSUE THREAD

**Issue by bucaran** [rafaelrinaldi/pure#6]
This theme works perfectly with:

* [fundle](https://github.com/tuvistavie/fundle)
* [Fisherman](https://github.com/fisherman/fisherman)
* [Wahoo](https://github.com/bucaran/wahoo)

and of course

* [Oh My Fish!](https://github.com/oh-my-fish/oh-my-fish)

Displaying the Oh My Fish! badge could potentially make new users believe that this theme does not work with others systems.

BTW I know the README was generated from a template that includes this badge (or the badges were taken from a template), as I worked in the original ones for Wahoo and also for [OMF](https://github.com/oh-my-fish/oh-my-fish/blob/2693a2fd18bd92a439f4d74b10513922d92120f7/pkg/omf/templates/pkg/README.md). I am just posting this to let you know of the issue.

Cheers! :smile:

**Comment by oranja** [comment]
I am all for healthy competition and agree with @bucaran. It would be more fair to list the different frameworks that the theme is known to work with than put the OMF badge and forget about the rest.
But just to be clear, I see nothing wrong with specifying several of them as officially supported and recommended, though, if the author chooses to. So far the frameworks are all pretty much compatible, but at some point there will probably be some considerable differences, or there's no reason for them all to coexist simultaneously.

**Comment by edouard-lopez** [comment]
Thanks for the feedback !

### Context
I reckon @rafaelrinaldi did not target any specific framework but the bare `fish` (correct me if I'm wrong).

The badge was added by my [pull request to add support for oh-my-fish](/rafaelrinaldi/pure/pull/5) as I did the port to OMF (which I use). 

As a result to my contribution @rafaelrinaldi grant me access to its repo recently.

### Keep Calm and Carry Coding

@bucaran @bucaran 
I'm all fair competition and supporting a zillion framework but we may lack **the resources to do so and finally give a poor experience to users**.
We can probably add support for other frameworks, but to do so we need people that can help resolve related issues. 

Are you interested ?

**Comment by bucaran** [comment]
Yo. What do you need to be done? A PR addressing the issue?

**Comment by edouard-lopez** [comment]
@bucaran that's a good beginning!

Are you familiar with any of the cited framework?

**Comment by bucaran** [comment]
I think I am familiar.

**Comment by rafaelrinaldi** [comment]
@bucaran Thanks for the heads up. As @edouard-lopez already said, I initially made this theme to work with a raw fish setup (I don't personally use any frameworks).
I'm glad to see it is well supported though! Feel free to submit a PR with instructions for installing the theme in all these different frameworks. That would be nice!

**Comment by bucaran** [comment]
Got it and thanks, will do. :+1:

**Comment by oranja** [comment]
rofl :joy:
I am sure @bucaran would love to help with anything related to Fisherman.

I would love to help with Oh-My-Fish.
Already suggested to rename the repository to **theme-pure** and back again to **pure**, just to create a redirection from **theme-pure** to **pure**, which would be very helpful to OMF.
\* We are aware that this is not a nice request and working on avoiding this issue, but for now this is our workaround...

**Comment by bucaran** [comment]
The name of the repository is not a problem. All I am suggesting is adding sections to either explain how to install it in other systems.

**Comment by oranja** [comment]
> The name of the repository is not a problem. All I am suggesting is adding sections to either explain how to install it in other systems.

Sadly it is a problem for OMF at this point in time. However, it is also not a problem to change it and then change it back to **pure**. See #7.

Don't get me wrong, I'll be the first one to +1 your PR with installation instructions for more frameworks.

**Comment by rafaelrinaldi** [comment]
@oranja I got you covered. Just closed #7 :+1:

**Comment by oranja** [comment]
Muchas gracias :pray:

**Comment by edouard-lopez** [comment]
@oranja @bucaran my bad I'm new to fish and just saw you are the main dev behind Fisherman and wahoo :P

**Comment by bucaran** [comment]
@edouard-lopez No problem. I used to contributed alot to Oh My Fish too.

![untitled](https://cloud.githubusercontent.com/assets/8317250/12265013/db0b9db2-b97d-11e5-83f0-d88473db4913.png)
