### ISSUE TITLE
Versionning

### ISSUE THREAD

**Issue by edouard-lopez** [rafaelrinaldi/pure#60]
@pierrebeaucamp @rafaelrinaldi I pushed some tags on the recent merges and feature additions loosely following [semver](https://semver.org/). 

So we are now on version `1.6.0` 🎉 !

Please consider tagging the project for upcoming feature additions :)

**Comment by edouard-lopez** [comment]
I'm creating [some releases](https://github.com/rafaelrinaldi/pure/releases).

I'm closing this issue as it's main purpose was to keep you guys up-to-date

**Comment by rafaelrinaldi** [comment]
@edouard-lopez Thanks a lot for the hard work Edouard.
