### ISSUE TITLE
Working Directory not printed on first run

### ISSUE THREAD

**Issue by andyperisho** [rafaelrinaldi/pure#62]
I looked in the code, and it seems that the current working directory is printed on top for the prompt everytime, unless if it's the first time fish is invoked.
Is there a way to change this behavior?

Also, I noticed that when I clear the screen, the prompt is on the third line. First line is empty, second line is the working directory. Any chance this empty line can also be removed?

Cheers

**Comment by edouard-lopez** [comment]
It's come from [preprompt](https://github.com/rafaelrinaldi/pure/blob/master/fish_prompt.fish#L78)

You're right, the new line is added [each time a prompt is displayed](https://github.com/rafaelrinaldi/pure/blob/master/fish_prompt.fish#L53-L56) except if it's a new session. It will be better if we could remove it on clear, you could have a look at the [original zsh theme](https://github.com/sindresorhus/pure/blob/master/pure.zsh) for help.

Feel free to submit a pull request :)

**Comment by andyperisho** [comment]
i realized that i didn't explain myself properly. What I actually wish for, is to have the CWD printed all the time, especially on the first run. No matter what kind of permutations I tried, I still didn't figure out how to make it happen!


Regarding the new line, after testing, I understand it's purpose when the screen is not meant to be cleared since it adds some space. I am not sure how to make it not add a line on clear since I never worked with fish scripts

**Comment by rafaelrinaldi** [comment]
I understand what you want but this behavior was purposefully added to be consistent with the original theme. Unless they've changed this to behave the way you expect either by default or via config, I would like to keep it as is for simplicity's sake.

You could probably try setting `pre_prompt` as a global variable under your own local fish config so it would take precedence over the value we set on the theme.

I'm closing the issue for now but feel free to open another one if I'm missing something here.

**Comment by andyperisho** [comment]
I managed to get the behavior I was looking for by adding
```
echo $pre_prompt
```

to my `fish.config`.

Cheers!
