### ISSUE TITLE
Option to make prompt 1 line

### ISSUE THREAD

**Issue by iamajvillalobos** [rafaelrinaldi/pure#65]
Is it possible to have an option to be like this? https://github.com/DFurnes/purer.

**Comment by rafaelrinaldi** [comment]
This comes up quite often actually. As I said a few times here before I personally would like to always stick to the original pure theme since the main idea of this project is to be a 1:1 from zsh to fish. If this is an option on the official theme (can you please check?) we can definitely look into supporting it (PRs welcome) but if not I'd like to stay out of it.

**Comment by iamarmanjon** [comment]
No :), I respect your decision still. Thank you for your efforts on this one. I'm closing this now.

**Comment by rafaelrinaldi** [comment]
Thank you for your suggestion. If you have anything else you would like to see in the project please feel free to open an issue.

**Comment by sholladay** [comment]
Hi @rafaelrinaldi, I found that the original Pure theme does in fact support this. Would you be willing to reconsider? I would like to at least try it out for a bit and see how it feels. A branch would be great, even if you don't want to publish it as part of an official release.

https://github.com/sindresorhus/pure/wiki#single-line-prompt

**Comment by edouard-lopez** [comment]
I re-open this as it's indeed a feature of the `zsh` version.

### Temporary Solution

You can test this by modifying [fish_prompt.fish#L5](https://github.com/rafaelrinaldi/pure/blob/master/fish_prompt.fish#L5) to not print newline, by adding a `-n` flag:

```diff
- echo -e (_pure_prompt_first_line) # print current path, git branch/status, command duration
+ echo -e -n (_pure_prompt_first_line) # print current path, git branch/status, command duration
```

### Long-term Solution

1. Add tests for required feature (can happen last if you are un-familiar with TDD) ;
1. Create a flag in `config/pure.fish`, _e.g._ `pure_enable_single_line_prompt` (default to `false`) ;
1. Alter the behavior in _fish_prompt.fish#L5_ based on flag (I prefer `printf` over `echo` for such thing) ;

@sholladay Would you be kind enough to submit a PR? You'll need

**Comment by sholladay** [comment]
Yes, I will explore making a PR for this.

**Comment by rafaelrinaldi** [comment]
@sholladay Thanks for chiming in. I’d be more than happy to review a PR for this.

**Comment by limakzi** [comment]
May I support you with this ticket, @sholladay, @rafaelrinaldi?

**Comment by sholladay** [comment]
I still intend to submit a PR for this when time allows. It's kind of low on my list, though, so if you're on the fence about working on it, don't wait for me. :)

That said, if someone were able to tackle step `1` and make a failing test case, I could certainly get to it sooner.

**Comment by IlanCosman** [comment]
Hi, just wanted to mention that [Tide](https://github.com/IlanCosman/tide) can do this. Just run Tide's configuration wizard and select the [Pure style](https://github.com/IlanCosman/tide#pure-compatibility).

Other advantages of Tide:

- Significantly more configurable
- Much faster (~4x) outside of git repos
- Multi-line right prompt
- Extensible

**Comment by NickHu** [comment]
Tide was quite buggy when I tried it so I'd still value someone adding this here

**Comment by edouard-lopez** [comment]
Zsh Pure put everything before the prompt symbol `❯` I'm going to implement it like this.

![](https://cloud.githubusercontent.com/assets/147409/25740894/294b9c20-3191-11e7-947f-b3ac1597f69f.png)
