### ISSUE TITLE
Update first line on "Alt + ←" and "Alt + →"

### ISSUE THREAD

**Issue by schrodincat** [rafaelrinaldi/pure#66]
**related:** #68 

---
Fish allows user to go back and forth in directory history with `Alt + ←` and `Alt + →`. Pure should update first line of the prompt containing current directory after changing it using those key combinations.

Right now, the directory on the first line updates to proper value only on the next prompt. Built-in prompts seem to update directory without any issues.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rafaelrinaldi** [comment]
@schrodincat Thanks for your suggestion. I had no idea this was possible. We will look into supporting this feature on `pure`.

In the meantime feel free to submit a PR if you feel like it.

**Comment by schrodincat** [comment]
@rafaelrinaldi I’ll do a PR, no problems👌 I’ve managed to fix this issue, but I’ve also noticed there is something fishy going on (couldn’t help myself, sorry, I’m new to fish 😅).
Is there any reason we evoking  `pre_prompt` through event handler? Because, it seems, it isn’t called when going through directory history. It is also not called on the terminal opening (at least for me with Terminal.app on macOS) which I believe is not intended behavior.


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by edouard-lopez** [comment]
Could you create a dedicated PR for this? Having a smaller scope helper review faster and release more frequently :+1:

**Comment by schrodincat** [comment]
@edouard-lopez no, I don’t think so, the underlying issue is the same as for https://github.com/rafaelrinaldi/pure/issues/68, so if you fix one, you fix other automatically...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
