### ISSUE TITLE
Different colors than the zsh-version

### ISSUE THREAD

**Issue by boyeborg** [rafaelrinaldi/pure#69]
**related:** #70 

---

Why are the default colors different from the ones used in [the zsh-version](https://github.com/sindresorhus/pure)?

**Comment by boyeborg** [comment]
I see. Would a pull request changing the colors to the ones used in the zsh version be welcome? I think it would make more sense to use the same colors, but I agree that it's not a big deal as they are easily configured by the individual user.

**Comment by boyeborg** [comment]
Great!

**Comment by rafaelrinaldi** [comment]
The work to support this is available in #70. Closing for now.
