### ISSUE TITLE
rename repo to theme-pure

### ISSUE THREAD

**Issue by edouard-lopez** [rafaelrinaldi/pure#7]
This is in order to [support OMF install](https://github.com/rafaelrinaldi/pure/issues/3#issuecomment-168689730) with 

    omf install pure

This is backward-compatible thanks [new Github feature](https://github.com/rafaelrinaldi/pure/issues/3#issuecomment-168696116) that [Automatic redirects for renamed repositories](https://developer.github.com/changes/2015-07-21-automatic-redirects-for-renamed-repositories/).

**Comment by rafaelrinaldi** [comment]
Done :+1:
