### ISSUE TITLE
Reset colors

### ISSUE THREAD

**Issue by heyarne** [rafaelrinaldi/pure#73]
I have played around a bit with the `fish_config` web interface and realized that now my colors are a bit off - what's the best way to revert the changes? I tried `grep`ping and unsetting the values I found in `set -U` but that left me without any colors on input, even after reinstalling this theme. Any advice?

**Comment by rafaelrinaldi** [comment]
I am not really sure I understand your question. It sounds like a local Fish configuration on your end. Is this a problem specific to this theme?

**Comment by edouard-lopez** [comment]
@heyarne you can [grab the colors assignment from `fish_prompt.fish`](https://github.com/rafaelrinaldi/pure/blob/master/fish_prompt.fish#L22-L32). It's not inside a function so copy/paste should do
