### ISSUE TITLE
Support Fundle

### ISSUE THREAD

**Issue by nesl247** [rafaelrinaldi/pure#76]
It would be great if https://github.com/tuvistavie/fundle was supported. It looks like the reason it isn't is a custom installation system is used instead of a more standard fish setup.

Edit: I have since tested this out, and by simply moving the functions to a `functions` directory, everything works. See https://github.com/nesl247/pure/tree/feature/fundle-support

**Comment by edouard-lopez** [comment]
Thanks @nesl247, I created a PR based on your code (cf. #77).

**Comment by rafaelrinaldi** [comment]
Thanks for the heads up @nesl247!

**Comment by edouard-lopez** [comment]
closed by #78

**Comment by nesl247** [comment]
Thanks for the fix.
