### ISSUE TITLE
fatal: repository 'pure' does not exist on Mac

### ISSUE THREAD

**Issue by joseluisq** [rafaelrinaldi/pure#8]
On Mac apparently pure repository doesn't exist:

![image](https://cloud.githubusercontent.com/assets/1700322/12270064/46390c16-b922-11e5-98d3-b6a62901a141.png)

**Comment by oranja** [comment]
Will be solved in a few hours. Sorry for the mislead.

**Comment by joseluisq** [comment]
@oranja great ! :+1:

**Comment by oranja** [comment]
It's done.
`omf update`, and you're good to `omf install pure`
Enjoy :beers:

**Comment by joseluisq** [comment]
Wow now works:
![image](https://cloud.githubusercontent.com/assets/1700322/12280137/b9f05af6-b959-11e5-8d46-e35f059e0316.png)

Thanks :+1:
