### ISSUE TITLE
Manual installation method is broken

### ISSUE THREAD

**Issue by schrodincat** [rafaelrinaldi/pure#81]
Script for manual installation is broken due to functions moved to separate directory

**Comment by edouard-lopez** [comment]
Hi @schrodincat,
you're right, I reckon the docker image I used for the tests give false positive.

I'm working on it, thanks :)

**Comment by schrodincat** [comment]
@edouard-lopez I've already fixed it in my PR: 
https://github.com/rafaelrinaldi/pure/pull/68

**Comment by edouard-lopez** [comment]
The test should've catch this, I'm working on it/

**Comment by edouard-lopez** [comment]
@schrodincat It should work now, can you review it? I also added tests on the installer, see [how to run them locally](https://github.com/rafaelrinaldi/pure/blob/master/installer.md).

You might need to update your PR #68

**Comment by schrodincat** [comment]
I can check it, but not before Tuesday, unfortunately😔

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by edouard-lopez** [comment]
Does this issue still stand?

**Comment by schrodincat** [comment]
> Does this issue still stand?

Yes

**Comment by edouard-lopez** [comment]
The current test for the manual install is invalid.
