### ISSUE TITLE
Overriding definition of `fish_right_prompt.fish`

### ISSUE THREAD

**Issue by filipebarros** [rafaelrinaldi/pure#87]
At the moment, installing this plugin always overrides the `fish_right_prompt.fish`.

Can we just remove the `fish_right_prompt.fish` so it doesn't change the user defined `fish_right_prompt.fish` ?

**Comment by jorgebucaran** [comment]
@filipebarros Yes, you can. If you are using Fisher as your package manager and want to override a file included with Pure, I recomend [customizing your installation prefix](https://github.com/jorgebucaran/fisher#changing-the-installation-prefix) too.

**Comment by rafaelrinaldi** [comment]
This is interesting... We do that to make sure the theme looks consistent accross the board but I can see this is annoying. Maybe we can keep overriding the file itself but instead of simply setting it to empty we can try to read it from the user environment. Something like:

```fish
set -l right_prompt (fish_right_prompt or "")
```

What do you think?

**Comment by rafaelrinaldi** [comment]
@filipebarros Would you be willing to open a PR with this implemented? I'd be happy to review it and merge it in.

**Comment by filipebarros** [comment]
sure, I'll give it a go

**Comment by edouard-lopez** [comment]
closed by #104, available in [`1.13.0`](https://github.com/rafaelrinaldi/pure/releases/tag/v1.13.0)
