### ISSUE TITLE
Prompt broken

### ISSUE THREAD

**Issue by benedictleejh** [rafaelrinaldi/pure#88]
After updating to the latest pure, the prompt seems completely broken. The line before the prompt doesn't show anymore, nor is a new line inserted before the next prompt.

![screen shot 2018-10-25 at 11 17 52](https://user-images.githubusercontent.com/1317666/47474045-dd302e00-d847-11e8-878e-73edc8aaa209.png)

![screen shot 2018-10-25 at 11 19 01](https://user-images.githubusercontent.com/1317666/47474051-e3260f00-d847-11e8-9152-eafd1f591c7b.png)

The second screenshot is with default settings (the arrow is missing for some reason). I've been trying to debug, but I'm not getting much in the way of useful error messages from anything. The only error messages I've gotten were:

1. After updating, there was an error about a missing `__format_time` function, which went away after restarting fish.
2. If a command errors, `test` complains about a `Missing argument at index 2`.

The second error could mean something, but without a line number and to look at, I can't really tease out which line is causing the error as they all look fine (at least in `fish_prompt.fish`).

Both screenshots were taken on a Mac, OS X 10.13.6, I am getting the same issue on Linux however, so it doesn't seem to be an OS issue.

**Comment by jorgebucaran** [comment]
@benedictleejh Please state your installation method (manual, Fisher, Oh My Fish, Fundle) and fish-shell version.

**Comment by jorgebucaran** [comment]
@benedictleejh It appears Oh My Fish is not copying Pure's [conf.d](https://github.com/rafaelrinaldi/pure/tree/master/conf.d) snippets to your fish directory (https://github.com/oh-my-fish/oh-my-fish/issues/646). Configuration snippets are the shell's canonical autorun mechanism since fish 2.3 (and 2.2 or older through [a shim](https://github.com/jorgebucaran/fisher/#legacy-fish-support)).



In the meantime, you have these options:

1. Wait until configuration snippet support is added to Oh My Fish
2. Copy the files in the [conf.d](https://github.com/rafaelrinaldi/pure/tree/master/conf.d) directory to `~/.config/fish/conf.d` and restart your shell
3. Use a different package manager (Fisher, Fundle, etc)

**Comment by jorgebucaran** [comment]
@benedictleejh Just in case, if the `XDG_CONFIG_HOME` environment variable is defined on your system, use `$XDG_CONFIG_HOME/fish` to find the path to your fish configuration directory.

**Comment by benedictleejh** [comment]
Hmm, copying the configuration snippet to `~/.config/fish/conf.d` only partially works: the directory shows up now, but the terminal starts with a bunch of errors, related to the `__pure_set_default` function, and `test` is still complaining. I suspect this is due to the load order of Oh My Fish and `conf.d` snippets; `conf.d` seems to be loaded before all of the Oh My Fish stuff, and that causes problems.

Also, it seems themes for Oh My Fish ignore an `init.fish` file, so trying to move `conf.d/pure.fish` to `init.fish` in the theme root has no effect.

I'll fiddle around a bit more and see if there can't be a semi-elegant workaround.

**Comment by benedictleejh** [comment]
Copying (or linking as I've chosen to do instead) does work, apparently. One of my machines had an older install of Oh My Fish which didn't use a `conf.d` snippet to load, instead using `config.fish`, so pure's snippet got loaded before Oh My Fish. A newer install had the `conf.d` snippet, so Oh My Fish got loaded, then pure, thanks to the load order of `conf.d` snippets.

So that's the workaround: linking/copying `pure.fish` from `$pure_root/conf.d` to `$fish_config/conf.d`. But Oh My Fish has to be loaded before pure.

I guess this suffices for now, until Oh My Fish gets around to properly handling `conf.d` snippets in plugins.

**Comment by jorgebucaran** [comment]
Cool. You can close now.

**Comment by jorgebucaran** [comment]
@benedictleejh Sounds good. Close?

**Comment by benedictleejh** [comment]
Yeah, closing should be fine. Also, a note somewhere that tells Oh My Fish users about the workaround would be great as well.

**Comment by tucq88** [comment]
I should never run `brew upgrade` :(( Fucking ruined my new year eve :((
