### ISSUE TITLE
Manual installation throws error on Mac

### ISSUE THREAD

**Issue by joseluisq** [rafaelrinaldi/pure#9]
Manual installation throws error:
https://github.com/rafaelrinaldi/pure#manually

```sh
fish: Unknown command '__parse_current_folder'
~/.config/fish/functions/fish_prompt.fish (line 1): __parse_current_folder
                                                    ^
in command substitution
	called on line 29 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input
```

**Comment by edouard-lopez** [comment]
I can't reproduce on Ubuntu `15.10` cc @rafaelrinaldi

**Comment by oranja** [comment]
@edouard-lopez to reproduce this problem I believe you need a Fish environment without **pure** and without it's functions in Fish's memory. Uninstall **pure** and `refresh` the shell to test.

The theme used to be all packed in one file. Now that it's split to several file, it's not possible to "install" it by downloading just one file. Proper install instructions should probably involve a `git clone` or at least downloading the repository as a zip file (https://github.com/rafaelrinaldi/pure/archive/master.zip).

I'm short on time right now, so I can't write complete instructions, but OMF (and possibly every other Fish framework) does something in the lines of:
1a. `git clone` (possibly with `--depth=1` for a quick shallow clone) into some <_folder_>.
1b. \***or**\* download (`curl`/`wget`) the zip & `unzip` into some `-C <folder>`.
2. "Autoload" the scripts in the theme folder with `set fish_function_path <folder> $fish_function_path`
3. `source <folder>/fish_prompt.fish`

Also, `.` is deprecated in Fish. Always use `source` instead.

**Comment by joseluisq** [comment]
> Also, . is deprecated in Fish. Always use source instead.

Yeah, dot doesn't work.

**Comment by edouard-lopez** [comment]
@oranja I'm working on an installer script, but hit a wall on the last step (sourcing `fish_prompt.fish`) as there is no lazy loading of other files.

**Comment by oranja** [comment]
> "Autoload" the scripts in the theme folder with set fish_function_path <folder> $fish_function_path
Did you add this step before sourcing?

**Comment by edouard-lopez** [comment]
@oranja yep, check out the [installer.fish](https://github.com/rafaelrinaldi/pure/blob/installer/installer.fish) on the _installer_ branch. I'm having the following error when running the installer while sourcing manually works:

    __parse_current_folder: command not found
    ~/.config/fish/functions/fish_prompt.fish (line 1): __parse_current_folder
                                                        ^
    in command substitution
            called on line 29 of file ~/.config/fish/functions/fish_prompt.fish
    
    in function “fish_prompt”
            called on standard input
    
    in command substitution
            called on standard input
    
    __parse_git_branch: command not found
    ~/.config/fish/functions/fish_prompt.fish (line 1): __parse_git_branch
                                                        ^
    in command substitution
            called on line 29 of file ~/.config/fish/functions/fish_prompt.fish
    
    in function “fish_prompt”
            called on standard input
    
    in command substitution
            called on standard input

**Comment by oranja** [comment]
By the time I figured out all the quirks, I already had a complete installer ready...
See #12

**Comment by joseluisq** [comment]
:+1:

**Comment by rafaelrinaldi** [comment]
Hey @joseluisq thanks for reporting this. We've made some improvements and fixes regarding the manual installation proccess and this issue might be fixed already. Can you please test with the latest version?

**Comment by joseluisq** [comment]
> Hey @joseluisq thanks for reporting this. We've made some improvements and fixes regarding the manual installation proccess and this issue might be fixed already. Can you please test with the latest version?

Yeah! I will try this on my workstation :)

**Comment by rafaelrinaldi** [comment]
@joseluisq Great! Hopefully this should have been fixed already but let us know, please.

**Comment by joseluisq** [comment]
Now works fine !
![image](https://cloud.githubusercontent.com/assets/1700322/13058571/0e339a4e-d3f2-11e5-95cb-5c1642cdeb92.png)
I will proceed to close this issue.
Good job!

:+1:

**Comment by rafaelrinaldi** [comment]
@joseluisq 

![alright](https://cldup.com/V0zQ5J2XO4.gif)
