### ISSUE TITLE
Prefix our functions to prevent conflict

### ISSUE THREAD

**Issue by edouard-lopez** [rafaelrinaldi/pure#90]
As discussed in [#68: Call prompt as a single function](https://github.com/rafaelrinaldi/pure/pull/68#discussion_r239424855):

> I’m also wondering if we should prefix them with pure or something similar, since those are available everywhere in fish. How we can sure it won’t collide with other user packages? Is it the job for the package manager or there is a naming convention we should adopt?

**Comment by jorgebucaran** [comment]
@edouard-lopez Yes, let's use `pure_*` (or if the function is "private", `_pure_*`) to prefix functions.

**Comment by edouard-lopez** [comment]
I will remove the prefix in filename but keep it in function name.

Is it ok with you? cc @rafaelrinaldi

**Comment by schrodincat** [comment]
I wonder if we should to assemble all pure functions in one file like fisher do, so it won't clutter functions folder. They have one `fisher.fish` file that have all fisher related functions.

**Comment by schrodincat** [comment]
> I will remove the prefix in filename but keep it in function name.

It won't work, fish autoloading mechanism demands functions to have the same name as the file name or it won't find it. It also means other functions inside this file are essentially private.

**Comment by jorgebucaran** [comment]
> I wonder if we should to assemble all pure functions in one file like fisher do, so it won't clutter functions folder. 

FYI I do that in Fisher to make Fisher's installation a simple file download and I consider it a special case. 

Generally, I would use one file per function. If you are using a package manager to install pure, it will handle moving `.fish` files in and out of your functions directory, so I am not bothered by pure's exporting more than one `.fish` function. 

Just my two cents, ultimately this is up to you.

**Comment by schrodincat** [comment]
I'm making a PR
